Add action for lint and test ui
aneoconsulting/ArmoniK.Admin.GUI pull request #10
Opened 2022-04-29 08:47 UTC by esoubiran-aneo

Create a new action to lint and test ui (libs)
Rename and add test to action app (apps) (from ci-angular to ci-apps-app)

2022-04-29 14:12 UTC, maurelleAneo requested changes

2022-04-29 14:12 UTC, maurelleAneo commented on .github/workflows/ci-apps-app.yml
> +      - "appps/app/**"
Un "p" en trop :)

2022-04-29 14:12 UTC, maurelleAneo commented on .github/workflows/ci-apps-app.yml
> +      - "appps/app/**"
Un "p" en trop également !

2022-05-02 14:49 UTC, esoubiran-aneo commented on .github/workflows/ci-apps-app.yml
> +      - "appps/app/**"
done

2022-05-04 08:59 UTC, maurelleAneo approved these changes

2022-05-04 08:59 UTC, merged