test: since date filter
aneoconsulting/ArmoniK.Admin.GUI pull request #185
Opened 2022-07-18 09:36 UTC by esoubiran-aneo

2022-07-19 08:33 UTC, maurelleAneo requested changes

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should have a property "name"', () => {
Tu ne testes pas les autres inputs ?

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +
Tu ne testes pas le ngOnInit ?

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should change the value', () => {
Tu devrais seulement tester que value te retourne bien selectedValue

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +
Tu ne testes pas isActive ?

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should create a new date if params is not defined', () => {
Tu ne testes pas cette fonction avec un argument concret pour tester que le retour est bon ?

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  });
Tu ne testes pas la fonction getDate ?

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should have a clr-select-container', () => {
Place tes tests dans un describe pour ceux qui sont relatifs à l'élément clr-select-container

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +    expect(compiled.querySelector('label')).toBeTruthy();
il manque le select element : expect(compiled.querySelector('select')).toBeTruthy();

2022-07-19 08:33 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should display a list of options', () => {
Ici tu devrais tester le contenu de ta liste d'options

2022-07-19 11:24 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should have a property "name"', () => {
c'est un oubli effectivement

2022-07-19 11:31 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +
done

2022-07-19 11:31 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +
done

2022-07-19 11:32 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should create a new date if params is not defined', () => {
Ah oui, c'est effectivement une bonne idée !

2022-07-19 11:32 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  });
Encore un oubli !

2022-07-19 11:32 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should have a clr-select-container', () => {
done

2022-07-19 11:34 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should display a list of options', () => {
Oulà oui, j'ai fait n'importe quoi ici !

2022-07-19 11:34 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +    expect(compiled.querySelector('label')).toBeTruthy();
Yes

2022-07-19 13:36 UTC, maurelleAneo requested changes

2022-07-19 13:36 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should change the value', () => {
Même remarque ici que dans la précédente PR

2022-07-19 13:36 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should return false when is not active', () => {
Pareil, englobe tes tests dans un describe

2022-07-19 14:29 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should change the value', () => {
yes ! Je vois le truc je crois

2022-07-19 14:30 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should return false when is not active', () => {
done

2022-07-19 15:21 UTC, maurelleAneo requested changes

2022-07-19 15:21 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should change the value', () => {
Pareil ici ^^ on veut juste tester que le getter value return component.selectedValue qu'il y ait modification ou non

2022-07-19 15:27 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should change the value', () => {
done

2022-07-19 15:32 UTC, maurelleAneo requested changes

2022-07-19 15:32 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  describe('active', () => {
isActive

2022-07-20 11:45 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  describe('active', () => {
done

2022-07-20 11:46 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/since-date-filter/since-date-filter.component.spec.ts
> +  it('should return the selectedValue with "value"', () => {
done

2022-07-21 06:39 UTC, maurelleAneo approved these changes

2022-07-21 06:39 UTC, merged