test: tasks list
aneoconsulting/ArmoniK.Admin.GUI pull request #195
Opened 2022-07-20 08:34 UTC by esoubiran-aneo

2022-07-21 07:14 UTC, maurelleAneo requested changes

2022-07-21 07:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +        console.log(seqLink);
console.log à supprimer

2022-07-21 07:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +        expect(seq.emit).toHaveBeenCalled();
tu peux ajouter le check avec le taskId

2022-07-21 07:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should have task id in modal title', () => {
Est-ce un besoin déterminant d'avoir l'erreur dans le body de la modal ?

2022-07-21 07:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should have task id in modal title', () => {
Le titre du test devrait être un peu différent (on parle de body et d'erreur)

2022-07-21 10:12 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +  describe('Seq', () => {
okkk, ça roule, c'est plus clair effectivement !

2022-07-21 10:13 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +        console.log(seqLink);
oups !

2022-07-21 10:14 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +        expect(seq.emit).toHaveBeenCalled();
effectivement !

2022-07-21 10:14 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should return "true" when status is cancelling', () => {
ah oui, je l'ai oublié !

2022-07-21 10:15 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should have task id in modal title', () => {
C'est à dire ? Je ne suis pas sûr d'avoir compris ?

2022-07-21 10:16 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should have task id in modal title', () => {
oui carrément, le titre n'avait rien à voir

2022-07-25 07:44 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +    it('should return task id when track by', () => {
Une tâche ayant forcément un id, j'ai retiré la possibilité d'utiliser l'index dans la fonction

2022-07-25 07:44 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should return "false" when status is not an error or pending', () => {
Effectivement, je vais le retirer

2022-07-25 07:45 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.spec.ts
> +      it('should have task id in modal title', () => {
Yes, du coup, commen on a pu voir, j'ai retiré la fonction

2022-07-26 07:26 UTC, maurelleAneo approved these changes

2022-07-26 07:26 UTC, merged