feat: add armonik logo
aneoconsulting/ArmoniK.Admin.GUI pull request #205
Opened 2022-07-25 12:06 UTC by esoubiran-aneo

2022-07-26 08:15 UTC, maurelleAneo requested changes

2022-07-26 08:15 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.html
> +          <img src="/assets/images/armonik-logo.png" alt="Logo d'ArmoniK" />
Mets plutôt "ArmoniK logo" en anglais

2022-07-27 08:03 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages.component.html
> +          <img src="/assets/images/armonik-logo.png" alt="Logo d'ArmoniK" />
Okk, je change ça

2022-07-27 08:23 UTC, maurelleAneo approved these changes

2022-07-27 08:24 UTC, maurelleAneo commented
Conflit à résoudre :)

2022-07-29 08:23 UTC, maurelleAneo approved these changes

2022-07-29 08:23 UTC, merged