test: sessions
aneoconsulting/ArmoniK.Admin.GUI pull request #212
Opened 2022-07-29 13:49 UTC by esoubiran-aneo

2022-08-02 07:34 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +      this.window.confirm(
Tu peux peut-être utiliser une modal pour cette confirmation ? ^^

2022-08-02 07:53 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +      this.window.confirm(
Une modale Clarity ?

2022-08-02 07:54 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +      this.window.confirm(
Mais en soit oui, je peux tout à fait faire ça, j'avoue avoir pris une solution facile !

2022-08-02 08:16 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +      this.window.confirm(
Yes, je pense que ce sera plus propre

2022-08-02 08:33 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +      this.window.confirm(
J'ai fait ça dans #215

2022-08-02 09:11 UTC, maurelleAneo requested changes

2022-08-02 09:11 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.spec.ts
> +  describe('cancelSession', () => {
Il faut donc changer ton test ici

2022-08-02 09:39 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.spec.ts
> +  describe('cancelSession', () => {
Yes je merge et je change ça !

2022-08-09 12:59 UTC, maurelleAneo approved these changes

2022-08-09 13:00 UTC, maurelleAneo commented
Certains conflits sont à résoudre :)

2022-08-09 14:37 UTC, merged