feat: save states from datagrid for fluid navigation
aneoconsulting/ArmoniK.Admin.GUI pull request #222
Opened 2022-08-08 10:09 UTC by esoubiran-aneo

2022-08-09 13:20 UTC, maurelleAneo requested changes

2022-08-09 13:20 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
> +  deleteState() {
N'oublie pas le void

2022-08-09 13:20 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
> +   * Get currant page
current

2022-08-09 13:20 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
>    excerpt(text: string): string {
si text peut être undefined, l'indiquer dans l'argument passé en entrée avec un "?"

2022-08-09 13:20 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +          "delete_state": "Delete table state",
En français

2022-08-09 14:26 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
> +   * Get currant page
Yes!

2022-08-09 14:26 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
> +  deleteState() {
done

2022-08-09 14:26 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
>    excerpt(text: string): string {
oui

2022-08-09 14:27 UTC, esoubiran-aneo commented on apps/app/src/assets/i18n/fr.json
> +          "delete_state": "Delete table state",
Oulà oui, ce n'est pas français ça !

2022-08-09 14:38 UTC, maurelleAneo commented
Il y a des conflits à merger :)

2022-08-11 10:12 UTC, maurelleAneo approved these changes

2022-08-11 10:12 UTC, merged