Add sessions
aneoconsulting/ArmoniK.Admin.GUI pull request #23
Opened 2022-05-11 13:58 UTC by esoubiran-aneo

- feat(sessions): add actions
- feat(sessions): add types

2022-05-17 13:59 UTC, maurelleAneo requested changes

2022-05-17 13:59 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/components/session-action/session-action.component.ts
> +  private serviceCall?: Observable<Session>;
Renommer en session$

2022-05-17 13:59 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/components/session-action/session-action.component.ts
> +export class SessionActionComponent {
Supprimer l'input closed pour gérer seulement l'état du bouton en lui-même

2022-05-17 13:59 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/components/session-errors/session-errors.component.ts
> +    return this.translateService.instant('sessions.errors.' + error.status, {
Tu peux écrire ça comme ça : 
`'sessions.errors.' + error.status` => \``sessions.errors.${error.status}`\`

2022-05-17 13:59 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/components/session-errors/session-errors.component.ts
> +    return index + error.status;
utilises juste l'index

2022-05-17 13:59 UTC, maurelleAneo commented on libs/armonik-typing/src/lib/entities/app-error.entity.ts
> +export type AppError = {
A mettre plutôt en front car utilisé uniquement par le front

2022-05-23 15:36 UTC, esoubiran-aneo commented
Useful for #41  but will be closed soon

2022-05-30 13:13 UTC, closed without merging