fead: load last three sessions with applications
aneoconsulting/ArmoniK.Admin.GUI pull request #231
Opened 2022-08-09 09:52 UTC by esoubiran-aneo

2022-08-09 14:26 UTC, maurelleAneo requested changes

2022-08-09 14:26 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/components/application-card/application-card.component.html
> +    <ul>
plutôt mettre un `*ngIf="application"` sur <ul> et enlever le `?` du `<li>`

2022-08-09 14:26 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/components/application-card/application-card.component.ts
> +  trackBySession(index: number) {
session n'a pas d'id ?

2022-08-09 14:26 UTC, maurelleAneo commented on libs/armonik-typing/src/lib/entities/application.entity.ts
> +    _id: string;
Ici tu ne peux pas utiliser le type FormattedSession ?

2022-08-09 14:33 UTC, esoubiran-aneo commented on libs/armonik-typing/src/lib/entities/application.entity.ts
> +    _id: string;
Non parce que je ne retroune pas les mêmes données depuis le serveur étant donnée que je n'ai besoin que de l'id, de la date de création et de la date d'annulation

2022-08-09 14:33 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/components/application-card/application-card.component.ts
> +  trackBySession(index: number) {
Elle en a un effectivement, je vais remplacer ça !

2022-08-09 14:44 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/components/application-card/application-card.component.html
> +    <ul>
carrément oui, ça sera plus propre !

2022-08-09 15:35 UTC, maurelleAneo approved these changes

2022-08-11 10:13 UTC, maurelleAneo approved these changes

2022-08-11 10:13 UTC, merged