fix: logger on server error
aneoconsulting/ArmoniK.Admin.GUI pull request #253
Opened 2022-09-12 13:11 UTC by esoubiran-aneo

2022-09-13 07:56 UTC, esoubiran-aneo commented
Check if it's working in install

2022-09-13 08:46 UTC, maurelleAneo requested changes

2022-09-13 08:46 UTC, maurelleAneo commented on apps/api/src/app/core/services/grpc-error.service.ts
>  export class GrpcErrorService {
Au lieu de faire ça dans un service en back, ne penses-tu pas que pourrais le faire dans un filter ? Comme ça tu pourrais throw les erreurs à la sortie de toutes les requetes de tous tes controller -> tu factorises plus facilement

2022-09-13 12:33 UTC, esoubiran-aneo commented on apps/api/src/app/core/services/grpc-error.service.ts
>  export class GrpcErrorService {
Yes ! Je garde l'idée mais ce n'est pas du tout l'objet de la PR qui vise à fix un bug assez critique où le logger n'est pas défini.

2022-09-13 14:36 UTC, maurelleAneo approved these changes

2022-09-14 07:16 UTC, maurelleAneo approved these changes

2022-09-14 07:16 UTC, merged