chore: update proto
aneoconsulting/ArmoniK.Admin.GUI pull request #260
Opened 2022-09-13 13:27 UTC by esoubiran-aneo

- chore: update proto
- chore: update package name

2022-09-13 13:28 UTC, esoubiran-aneo commented
Waiting for #253 before merging

2022-09-13 14:51 UTC, maurelleAneo submitted a review, later dismissed

2022-09-14 08:20 UTC, esoubiran-aneo commented
Because of a change in TaskOptions, https://github.com/aneoconsulting/ArmoniK.Api/blob/main/Protos/V1/objects.proto#L12, database call must be changed

2022-09-14 14:48 UTC, maurelleAneo requested changes

2022-09-14 14:48 UTC, maurelleAneo commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +      taskSort['StartDate'] = -1;
Majuscule à Start ?

2022-09-14 14:48 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
> +    clrDgField="_id"
ce n'est pas "id" ici ?

2022-09-15 07:26 UTC, esoubiran-aneo commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +      taskSort['StartDate'] = -1;
`startAt`, c'est le nom que je donne après transformation de la donnée, [juste ici](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/blob/main/apps/api/src/app/modules/tasks/tasks.service.ts#L88) !

Mais il se trouve aussi, et je n'avais pas fait attention à cela, le projection (c'est le nom de changement de la structure de données avec mongo), se fait en dernier, même avec un `find`. Du coup, il n'est pas possible d'utiliser le nom des clés qui résultent de la projection pour faire un `sort` ! Donc il faut utiliser la clé qui est en base.

2022-09-15 07:28 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
> +    clrDgField="_id"
Et du coup, le nom qui doit être ici, est celui qui est envoyé et directement mis dans le champs qui trie les data. Il doit correspondre à la clé présente dans la base de données `_id`.

Il est vrai que l'on pourrait faire des transformations mais comme tout cela va évoluer très très vite, je préfère garder cela simple et logique avec le reste des choses déjà implémentées.

2022-09-15 07:49 UTC, maurelleAneo commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +      taskSort['StartDate'] = -1;
D'accord, je t'avoue qu'avec des bribes de codes à checker je n'ai pas la globalité du fonctionnement ^^' mais ça marche pour moi

2022-09-15 07:51 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
> +    clrDgField="_id"
Ca marche

2022-09-15 07:51 UTC, maurelleAneo approved these changes

2022-09-15 07:57 UTC, merged