feat: create results endpoints
aneoconsulting/ArmoniK.Admin.GUI pull request #265
Opened 2022-09-15 10:15 UTC by esoubiran-aneo

2022-09-22 07:50 UTC, maurelleAneo requested changes

2022-09-22 07:50 UTC, maurelleAneo commented on apps/api/src/app/modules/results/results.service.ts
> +        total, // Total number of sessions
sessions ou results ici ?

Result est une entité à part entière qui représente quoi exactement ?

2022-09-22 07:50 UTC, maurelleAneo commented on apps/api/src/app/modules/results/schemas/results.schema.ts
> +@Schema({
Tu devrais renommer ton fichier : `result.schema.ts`
Car le nom de ton schema et de ta classe sont au singulier

2022-09-22 07:50 UTC, maurelleAneo commented on apps/api/src/app/modules/results/results.service.ts
> +    // TODO: Implement filters
Quels filtres sont à implémenter ? Et pourquoi tu ne les as pas implémentés sur cette PR ? :)

2022-09-22 07:50 UTC, maurelleAneo commented on apps/api/src/app/modules/tasks/tasks.controller.ts
> +  @ApiNotFoundResponse({ description: 'Not found' })
Ici tu ne mets pas la doc pour les codes 200 ? Ni pour faire la description globale des appels ?

2022-09-22 07:50 UTC, maurelleAneo commented on apps/api/src/app/modules/tasks/tasks.controller.ts
> +  async findResults(@Param('taskId') taskId: string) {
findAllResultsByTaskId

2022-09-22 07:50 UTC, maurelleAneo commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +    return this.resultModel.find({ OwnerTaskId: taskId }).exec();
Pas de filtres ici ?
Ni de order, page,... ?

2022-09-22 07:53 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/results.service.ts
> +    // TODO: Implement filters
C'est des filtres sur les colonnes. Je ne l'ai pas fait dans cette PR pour éviter qu'elle soit trop grosse. Mais si tu pense que je dois le fait ici je peux

2022-09-22 07:53 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/schemas/results.schema.ts
> +@Schema({
Yes, tout à fait !

2022-09-22 07:54 UTC, maurelleAneo commented on apps/api/src/app/modules/results/results.service.ts
> +    // TODO: Implement filters
Je pense que tu devrais les implémenter maintenant, comme ça tout est fait et tu n'as plus besoin de revenir dessus tout de suite :)

2022-09-22 14:46 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/results.service.ts
> +        total, // Total number of sessions
C'est une erreurs. Les résultats sont bien des entités à part entière.

2022-09-22 14:46 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/results.service.ts
> +    // TODO: Implement filters
ça marche, je vais faire ça prochainement.

2022-09-26 11:48 UTC, esoubiran-aneo commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +    return this.resultModel.find({ OwnerTaskId: taskId }).exec();
La question sous entendue étant de savoir s'il faut paginer ou non les résultats ? @aneojgurhem

2022-09-26 11:54 UTC, aneojgurhem commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +    return this.resultModel.find({ OwnerTaskId: taskId }).exec();
Il n'y a pas de limite sur le sujet. Trois choses :
 - si ça revoit juste l'id, ce ne sont que des GUIDs donc ça devrait être raisonnable en taille
 - Ext ne prévoit qu'un résultat par tache à l'heure actuelle.
 - En pratique, je ne pense pas qu'il y ait plus de quelques dizaines de résultats par tache.
Tout ça pour dire que je ne vois pas l'intérêt de paginer pour l'instant.

2022-09-26 12:16 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/results.service.ts
> +    // TODO: Implement filters
C'est bon !

2022-09-26 12:16 UTC, esoubiran-aneo commented on apps/api/src/app/modules/tasks/tasks.controller.ts
> +  @ApiNotFoundResponse({ description: 'Not found' })
done

2022-09-26 12:23 UTC, esoubiran-aneo commented on apps/api/src/app/modules/tasks/tasks.service.ts
> +    return this.resultModel.find({ OwnerTaskId: taskId }).exec();
Et que donc ça sera paginé

2022-09-28 07:43 UTC, maurelleAneo requested changes

2022-09-28 07:43 UTC, maurelleAneo commented on apps/api/src/app/modules/results/results.controller.ts
>    ) {
Il manque le type de retour et la description de ton appel pour le Swagger

2022-09-28 07:43 UTC, maurelleAneo commented on apps/api/src/app/modules/results/results.service.ts
> +    const match: { [key: string]: any } = {};
Ici tu peux peut-être utiliser : `const match: Record<string, any> = {}`

2022-09-28 07:43 UTC, maurelleAneo commented on apps/api/src/app/modules/results/results.service.ts
> +    const sort: { [key: string]: 1 | -1 } = {};
Pareil ici je pense

2022-09-28 13:42 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/results.service.ts
> +    const match: { [key: string]: any } = {};
Yes ! C'est plus propre

2022-09-28 13:43 UTC, esoubiran-aneo commented on apps/api/src/app/modules/results/results.service.ts
> +    const sort: { [key: string]: 1 | -1 } = {};
yes, plus propre

2022-10-04 07:22 UTC, maurelleAneo approved these changes

2022-10-04 07:22 UTC, merged