feat: add history
aneoconsulting/ArmoniK.Admin.GUI pull request #272
Opened 2022-10-11 12:21 UTC by esoubiran-aneo

2022-10-18 07:57 UTC, maurelleAneo requested changes

2022-10-18 07:57 UTC, maurelleAneo commented on apps/app/src/app/core/core.module.ts
> +    },
Pourquoi tu le provides ici ?

2022-10-18 07:57 UTC, maurelleAneo commented on apps/app/src/app/core/services/history.service.ts
> +    return history$.pipe(map((history) => [...history].reverse()));
Pourquoi tu reverse ici ?

2022-10-18 07:57 UTC, maurelleAneo commented on apps/app/src/app/core/core.module.ts
> +import { HistoryService } from './services/history.service';
Ce service n'est pas présent dans le fichier index qui puisse lui permettre d'être importé avec les services précédents ?

2022-10-18 07:57 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.ts
> +    this.router.events.subscribe((event) => {
Ici tu pourrais faire un `.filter` avant ton subscribe pour garder les événements de type navigationEnd au lieu de faire un if, et ajouter un `distinctUntilChanged` entre deux navigations pour éviter d'avoir à enregistrer les refresh de pages

2022-10-18 08:14 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/history.service.ts
> +    return history$.pipe(map((history) => [...history].reverse()));
Parce que je me dis que l'historique comporte en premier item le plus récent.

2022-10-18 08:15 UTC, esoubiran-aneo commented on apps/app/src/app/core/core.module.ts
> +import { HistoryService } from './services/history.service';
Si si tout à fais. Il faut que je l'ajoute dans l'index

2022-10-18 08:23 UTC, esoubiran-aneo commented on apps/app/src/app/core/core.module.ts
> +    },
ça permet ensuite de faire les tests plus simplement, notamment pour faire un mock du localStorage

2022-10-18 15:52 UTC, maurelleAneo commented on apps/app/src/app/core/core.module.ts
> +    },
Tu as déjà fait des tests avec un localStorage, c'est comme ça que tu avais fait également ? Sinon il faudrait juste le mocker dans ton fichier de test directement

2022-10-18 21:39 UTC, esoubiran-aneo commented
Il faut que je me renseigne sur la manière de faire

Estéban Soubiran
________________________________
From: maurelle-aneo ***@***.***>
Sent: Tuesday, October 18, 2022 5:52:22 PM
To: aneoconsulting/ArmoniK.Admin.GUI ***@***.***>
Cc: Estéban SOUBIRAN (ANEO) ***@***.***>; Assign ***@***.***>
Subject: Re: [aneoconsulting/ArmoniK.Admin.GUI] feat: add history (PR #272)


@maurelleAneo commented on this pull request.

________________________________

In apps/app/src/app/core/core.module.ts<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faneoconsulting%2FArmoniK.Admin.GUI%2Fpull%2F272%23discussion_r998423950&data=05%7C01%7Cesoubiran%40aneo.fr%7C31831c3b0de246b86e6608dab120bf9d%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C638017051474272285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YyLtjayE3FV74ull2KsPhRml%2Bj5eFdMj0gabqIHzRe8%3D&reserved=0>:

>      ApiService,

     ErrorService,

     ApplicationsService,

     SessionsService,

     TasksService,

     PagerService,

     SeqService,

+    {

+      provide: Storage,

+      useFactory: () => localStorage,

+    },



Tu as déjà fait des tests avec un localStorage, c'est comme ça que tu avais fait également ? Sinon il faudrait juste le mocker dans ton fichier de test directement

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faneoconsulting%2FArmoniK.Admin.GUI%2Fpull%2F272%23discussion_r998423950&data=05%7C01%7Cesoubiran%40aneo.fr%7C31831c3b0de246b86e6608dab120bf9d%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C638017051474428532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gnu1tHDxM%2ByZsAAL9EIYPCibmmQ3LRTuscag9yxRC5g%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYZOASES3QULZWQRN6SDVJ3WD3BTNANCNFSM6AAAAAARCHLD6A&data=05%7C01%7Cesoubiran%40aneo.fr%7C31831c3b0de246b86e6608dab120bf9d%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C638017051474428532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7QNxrqxztfWn575%2Fgc4sg%2Bg%2FZTAERo4FY6OL8kagCVQ%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-10-19 13:24 UTC, esoubiran-aneo commented on apps/app/src/app/core/core.module.ts
> +    },
L'idée c'est de faire ça https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/282. Comme ça, c'est beaucoup plus simple de tester puisque tu passes par l'injectiion de dépendances et non par un outil propre au navigateur.

2022-11-02 08:51 UTC, maurelleAneo submitted a review, later dismissed

2022-11-02 08:51 UTC, maurelleAneo commented
Conflits à résoudre

2022-11-02 10:37 UTC, maurelleAneo approved these changes

2022-11-02 10:37 UTC, merged