feat: add icons before nav items
aneoconsulting/ArmoniK.Admin.GUI pull request #276
Opened 2022-10-13 14:22 UTC by esoubiran-aneo

2022-10-19 11:12 UTC, maurelleAneo requested changes

2022-10-19 11:12 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.ts
> -  links: AppNavLink[] = [
Pourquoi tu ne gardes pas ton type AppNavLink pour y rajouter l'icone à afficher ?

2022-11-02 09:01 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.ts
> -  links: AppNavLink[] = [
Apparemment, tu pourrais utiliser `[attr.shape]="tonicone"` pour qu'Angular interprète shape comme un input de clr-icon. Si cela fonctionne je pense que ce sera plus pratique de continuer à utiliser ton type AppNavLink

2022-11-02 09:01 UTC, maurelleAneo commented
Il va y avoir des conflits à résoudre sur cette branche

2022-11-02 11:00 UTC, maurelleAneo requested changes

2022-11-02 11:00 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.html
> +      <a clrVerticalNavLink href="/seq/" target="_blank">
Tu ne peux pas l'intégrer dans ton tableau de links ?

2022-11-02 11:00 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.html
> +      <a clrVerticalNavLink href="/grafana/" target="_blank">
Tu ne peux pas l'intégrer dans ton tableau de links ?

2022-11-02 11:00 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.html
>        <a clrVerticalNavLink routerLink="/how-to-use" routerLinkActive="active">
Tu ne peux pas l'intégrer dans ton tableau de links ?

2022-11-02 12:20 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages.component.html
> +      <a clrVerticalNavLink href="/seq/" target="_blank">
Il y a le divider qui permet une séparation visuel et je trouverais ça étrange de devoir le gérer dans mon NavLinks

2022-11-02 12:23 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages.component.html
> +      <a clrVerticalNavLink href="/grafana/" target="_blank">
Il y a aussi une séparation visuelle, du coup, ça sera un peu étrange de l'avoir dans le même tableau et ce son des liens externes.

2022-11-02 12:25 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages.component.html
>        <a clrVerticalNavLink routerLink="/how-to-use" routerLinkActive="active">
![image](https://user-images.githubusercontent.com/103997512/199488958-a86c14ad-6cf9-481f-bc7b-5a084c70b734.png)

Tu penses qu'il faut que j'intègre les séparateurs visuels dans mon tableau de links ?

2022-11-14 08:36 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.html
>        <a clrVerticalNavLink routerLink="/how-to-use" routerLinkActive="active">
Non puisqu'en  plus pour les favoris ce n'est pas un lien, laisse comme ça je pense

2022-11-14 08:37 UTC, merged