feat: check if seq and grafana are up
aneoconsulting/ArmoniK.Admin.GUI pull request #283
Opened 2022-10-19 14:16 UTC by esoubiran-aneo

2022-11-02 09:09 UTC, maurelleAneo requested changes

2022-11-02 09:09 UTC, maurelleAneo commented on apps/app/src/app/core/services/http/grafana.service.ts
> +        return { ok: res.ok, service: 'grafana' };
Pour cela tu devrais créer un fichier appelé `type.ts` à la racine de http afin d'y mettre un type contenant tes deux attributs. Tu pourra ainsi réutiliser ce type dans tes différents services et composants, ce sera plus facile à gérer et plus adaptable si besoin

2022-11-02 09:09 UTC, maurelleAneo commented on apps/app/src/app/core/services/http/grafana.service.ts
> +        return { ok: res.ok, service: 'grafana' };
De la même manière tu pourrais créer un fichier `services.enum` afin d'y lister tes différents types de services : grafana et seq, et réutiliser cet énum partout où tu fais une comparaison ` === 'grafana'` ou ` === 'seq'`

2022-11-02 09:09 UTC, maurelleAneo commented on apps/app/src/app/pages/pages.component.ts
> +  public get isSeqEnabled(): boolean {
N'oublie pas de rajouter dans ton fichier de test de pages la présence ou non de tes liens grafana et seq sur ton html si le service est up (en le mockant)

2022-11-02 11:16 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/http/grafana.service.ts
> +        return { ok: res.ok, service: 'grafana' };
yes carrément bien vu !

2022-11-02 11:16 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/http/grafana.service.ts
> +        return { ok: res.ok, service: 'grafana' };
c'est effectivement mieux de faire cela !

2022-11-02 13:12 UTC, maurelleAneo requested changes

2022-11-02 13:12 UTC, maurelleAneo commented on apps/app/src/app/core/enums/external-services.ts
> +export enum ExternalServices {
La bonne pratique est de nommer ton enum : `ExternalServicesEnum`
Et de nommer ton fichier : `external-services.enum.ts`
Comme ça on a toutes les infos d'un seul coup d'oeil, que ce soit en lisant le nom de ton fichier ou le nom de ton type

2022-11-02 13:12 UTC, maurelleAneo commented on apps/app/src/app/core/services/http/types.ts
> +  ok: boolean;
Ce serai peut être plus parlant de nommer cet attribut `response`

2022-11-03 08:26 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/http/types.ts
> +  ok: boolean;
sur un attribut `response` je m'attends à avoir toute la réponse.

2022-11-03 08:28 UTC, esoubiran-aneo commented on apps/app/src/app/core/enums/external-services.ts
> +export enum ExternalServices {
Effectivement, c'était mal nommé !

2022-11-04 16:39 UTC, maurelleAneo approved these changes

2022-11-04 16:39 UTC, merged