feat: link sessions to grpc
aneoconsulting/ArmoniK.Admin.GUI pull request #284
Opened 2022-10-20 13:08 UTC by esoubiran-aneo

2022-10-25 12:39 UTC, esoubiran-aneo commented on apps/app/src/assets/i18n/en.json
> +    "cells": {
Add .status.

2022-10-25 12:54 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +          {{ 'sessions.cells.' + session.status | translate }}
Add colors

2022-10-25 13:22 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +            [queryParams]="{ sessionId: session.sessionId }"
Add to the same route

2022-11-02 10:04 UTC, maurelleAneo requested changes

2022-11-03 09:17 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +                session.status
C'est pour faciliter la lecture parce que dans la bdd, c'est un number et pour ceux qui use à la fois la gui et d'autres outils, au moins, ils ne sont pas perdu et ça leur facilite la vie. (C'est du vécu le fait de demander "mais c'est statut 'completed' mais c'est quoi la valeur ?"

2022-11-03 09:18 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +          <ng-template #empty> - </ng-template>
Yes carrément, j'avoue que je ne savais pas trop où je pouvais le mettre.

2022-11-03 09:19 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-pager.service.ts
> +    params.set('page', page.toString());
Effectivement, je vais retravailler tout cela parce que utiliser HttpParams, ça ne fait pas sens finalement.

2022-11-03 09:24 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +                'text-success': session.status === 1,
Sisi, mais j'ai pas du tout pensé à l'utiliser alors que je le fais au dessus sur le orderby et le order !

2022-11-03 09:27 UTC, esoubiran-aneo commented on apps/app/src/app/core/types/app-nav-link.ts
> +  queryParams: Record<string, string | number | boolean>;
Il se trouve que `QueryParams` peut être null donc même pas besoin de l'objet vide.

2022-11-03 09:33 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
>    selector: 'app-pages-sessions-list',
Sisi, et du coup, un double router-outlet. J'ai une issue qui track ça donc je vais faire un patch bientôt.

2022-11-03 09:48 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +        [clrDgPageSize]="(queryParam$('pageSize') | async) || 10"
yes, je vois mais la problématique est qu'il faut que le `clr-dg-pagination`  soit sur la page. Or, un `*ngIf` bloque jusqu'à résolution de l'observable et le footer du datagrid ne s'affiche pas.

2022-11-04 16:45 UTC, maurelleAneo commented on apps/app/src/assets/i18n/en.json
> +  "sessions": {
Attention tu dois également le faire dans le fichier fr.json

2022-11-04 16:49 UTC, maurelleAneo requested changes

2022-11-04 16:49 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +        [clrDgPageSize]="(queryParam$('pageSize') | async) || 10"
Tu as essayé le bout de code ?
Car dans l'explication donnée, il est indiqué que le ngIf est toujours true même si aucun observable n'est run, du fait que ce soit un objet construit :
"In this case, the value of *ngIf will always be thruthy — even when none of the observables emit values. That means that all code inside the container will always be displayed. When the observables start emitting values, we will see their results."

2022-11-04 16:49 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +        [clrDgPageSize]="(queryParam$('pageSize') | async) || 10"
Tu as essayé le bout de code ?
Car dans l'explication donnée, il est indiqué que le ngIf est toujours true même si aucun observable n'est run, du fait que ce soit un objet construit :
"In this case, the value of *ngIf will always be thruthy — even when none of the observables emit values. That means that all code inside the container will always be displayed. When the observables start emitting values, we will see their results."

2022-11-04 16:49 UTC, maurelleAneo commented
Conflits à résoudre

2022-11-04 16:50 UTC, maurelleAneo requested changes
Voir mes réponses

2022-11-07 07:59 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +        [clrDgPageSize]="(queryParam$('pageSize') | async) || 10"
Yes j'ai essayé mais ça ne fonctionne pas. Mais je pense que en théorie ça marche mais que comme derrière on travaille avec Clarity, il y a des comportements inattendu. Je pense que la résolution du *ngIf intervient après que Clarity ait besoin de son footer. Je me renseigne plus en détail.

2022-11-07 08:31 UTC, esoubiran-aneo commented on apps/app/src/assets/i18n/en.json
> +  "sessions": {
ha yes, j'ai oublié 😟

2022-11-14 08:43 UTC, maurelleAneo commented on apps/app/src/assets/i18n/en.json
> +    "sessions-list": {
Tu devrais placer la partie "favorites" après le bloc "sessions-list" comme dans le fichier fr.json pour que les numéros de lignes correspondent. Ce sera ainsi plus facile à voir s'il te manque des traductions dans l'un ou l'autre des fichiers

2022-11-14 08:43 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +        [clrDgPageSize]="(queryParam$('pageSize') | async) || 10"
D'accord, étrange mais laisse comme ça du coup

2022-11-14 08:45 UTC, maurelleAneo commented
Conflits à résoudre

2022-11-14 10:39 UTC, esoubiran-aneo commented on apps/app/src/assets/i18n/en.json
> +    "sessions-list": {
Oulà, bien vu ça. Ce n'était pas du tout à la bonne place dans le fichier FR !

2022-11-14 11:22 UTC, maurelleAneo approved these changes

2022-11-14 11:22 UTC, merged