feat: fetch tasks using grpc
aneoconsulting/ArmoniK.Admin.GUI pull request #286
Opened 2022-10-25 12:59 UTC by esoubiran-aneo

2022-11-21 08:54 UTC, maurelleAneo requested changes

2022-11-21 08:54 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/tasks-list/tasks-list.component.ts
> +export class TasksListComponent implements OnInit {
N'oublie pas que pour chacune de tes variables, il faut que tu précise le type (même s'il semble évident) et de même pour l'ensemble de tes fonctions

2022-11-21 08:54 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/tasks-list/tasks-list.component.ts
> +  private _triggerDatagrid$ = this._subjectDatagrid.asObservable().pipe(
On ne mixe pas les promise et les observables normalement. Il me semble qu'il s'agit d'une mauvaise pratique. Je vais me renseigner plus là dessus pour t'apporter plus de précisions et sur la solution à envisager pour cet observable.

Par ailleurs, à quoi te sert-il exactement ?

2022-11-21 08:54 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +      "title": "Tasks",
Tasks en français aussi (comme je vois qu'il n'est traduit nulle part) ?

2022-11-21 08:54 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +        "ended_at": "Fin le",
`Terminée le` ?

2022-11-21 08:54 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +          "5": "Error",
`Erreur` ?

2022-11-21 08:54 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +        }
Cette accolade devrait être fermée juste après la ligne 118, car `auto_refresh` ne contient pas les clés : 
- "details"
- "related_results"
- "parent_session"
- "view_seq"

2022-11-21 09:24 UTC, esoubiran-aneo commented on apps/app/src/app/core/core.module.ts
> +import { GrpcTasksService } from './services/grpc/grpc-tasks.service';
J'aime pas trop faire un` import *`, là au moins, je suis sûr de ce qui est importé et utilisé.

2022-11-21 09:31 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/tasks-list/tasks-list.component.ts
> +  private _triggerDatagrid$ = this._subjectDatagrid.asObservable().pipe(
Tu parles du `concatMap` ?

2022-11-21 09:31 UTC, esoubiran-aneo commented on apps/app/src/assets/i18n/fr.json
> +      "title": "Tasks",
c'est une erreur ça parce que ça se traduit !

2022-11-21 09:34 UTC, esoubiran-aneo commented on apps/app/src/assets/i18n/fr.json
> +        }
Ho oui, bien vu !

2022-11-22 09:11 UTC, maurelleAneo approved these changes

2022-11-22 13:43 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-tasks.service.ts
> +  private _timeout$ = timer(8_000).pipe(
Okkk, c'est ce que j'ai fait du coup, dans la class `BaseGrpc`

2022-11-22 14:28 UTC, maurelleAneo requested changes

2022-11-22 14:28 UTC, maurelleAneo commented on apps/app/src/app/core/services/grpc/base-grpc.service.ts
> +export class BaseGrpc {
Attention au nom de ta classe, ton fichier est en `.service` donc le nom se termine par `Service ` :)

2022-11-22 14:28 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/tasks-list/tasks-list.component.ts
> +  public get isSeqUp$() {
N'oublie pas de préciser le type de retour de ton get

2022-11-23 09:02 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/base-grpc.service.ts
> +export class BaseGrpc {
Effectivement, je suis allé un peu vite !

2022-11-23 09:02 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/base-grpc.service.ts
> +export class BaseGrpc {
C'est changé

2022-11-28 11:04 UTC, maurelleAneo approved these changes

2022-11-28 11:04 UTC, merged