feat: fetch results using grpc
aneoconsulting/ArmoniK.Admin.GUI pull request #287
Opened 2022-10-25 15:12 UTC by esoubiran-aneo

2022-11-21 09:03 UTC, maurelleAneo requested changes

2022-11-21 09:03 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +          "parent_task": "Task"
Cette clé ne fait pas partie de la clé `auto-refresh`. Il faut fermer l'accolade de la ligne 113 avant

2022-11-22 09:13 UTC, maurelleAneo approved these changes

2022-11-22 09:13 UTC, maurelleAneo commented
Quand tu aura écris ta classe à étendre pour le service GRPC des résultats on pourra adapter et merger cette PR :)

2022-11-28 13:47 UTC, esoubiran-aneo commented
> Quand tu aura écris ta classe à étendre pour le service GRPC des résultats on pourra adapter et merger cette PR :)

Yes, c'est ce que j'ai fait !

2022-11-29 08:28 UTC, maurelleAneo approved these changes

2022-11-29 09:04 UTC, merged