feat: fetch applications using grpc
aneoconsulting/ArmoniK.Admin.GUI pull request #288
Opened 2022-10-27 12:47 UTC by esoubiran-aneo

2022-11-28 14:01 UTC, esoubiran-aneo commented
@esoubiran-aneo tu dois la faire rapidement pour réussir à virer ce qu'il ne faut pas !

2022-12-01 14:09 UTC, maurelleAneo requested changes

2022-12-01 14:09 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +          applications.application && applications.application.length > 0;
ici tu ne peux pas simplifier et utiliser le getter `hasApplications` ?

2022-12-01 14:09 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +          *ngFor="let application of applications.application"
trackBy manquant

2022-12-01 14:09 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +      class="applications__grid__spinner"
Tu ne mets pas le spinner dans le template de loading ?

2022-12-01 14:09 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +    <ng-template #loading>
Tu peux placer le template à la fin du fichier, car les templates sont globaux. Comme ça tu sais où ils sont sans devoir les chercher

2022-12-05 08:17 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +          applications.application && applications.application.length > 0;
Le `hasApplications` est sur le total (donc l'ensemble des applications de la base) alors que là, on regarde simplement si on a reçu des applications

2022-12-05 08:18 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +          *ngFor="let application of applications.application"
yes, je l'ajoute

2022-12-05 08:23 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +    <ng-template #loading>
En effet, ça va faciliter la lecture !

2023-03-06 09:39 UTC, closed without merging