feat: fetch applications using grpc
aneoconsulting/ArmoniK.Admin.GUI pull request #289
Opened 2022-10-27 13:59 UTC by esoubiran-aneo

fix: https://github.com/aneoconsulting/ArmoniK/issues/671
fix: https://github.com/aneoconsulting/ArmoniK/issues/673
fix: https://github.com/aneoconsulting/ArmoniK/issues/674
fix: https://github.com/aneoconsulting/ArmoniK/issues/666
fix https://github.com/aneoconsulting/ArmoniK/issues/691

2022-11-21 09:14 UTC, maurelleAneo requested changes

2022-11-21 09:14 UTC, maurelleAneo commented on apps/app/src/app/core/core.module.ts
> +import {} from './services/grpc/grpc-applications.service';
Mal exporté ici

2022-11-21 09:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages-routing.module.ts
> +        path: 'applications-2',
Pourquoi ce nom ?

2022-11-21 09:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/applications-list/applications-list.component.html
> +      <clr-dg-row *ngFor="let application of list.application">
TrackBy manquant

2022-11-21 09:14 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/applications-list/applications-list.component.ts
> +  private _triggerDatagrid$ = this._subjectDatagrid.asObservable().pipe(
Pareil ici

2022-11-21 09:14 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +        "applications": "{{value}} résultats",
`applications`

2022-11-21 09:14 UTC, maurelleAneo commented on apps/app/src/assets/i18n/fr.json
> +        "application": "{{value}} résultat"
`application`

2022-11-23 12:33 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-applications.service.ts
> +export class GrpcApplicationsService {
Il faudra utiliser le BaseGrpcService

2022-12-13 16:38 UTC, closed without merging