Refactor: seq & graphana settings
aneoconsulting/ArmoniK.Admin.GUI pull request #298
Opened 2022-11-10 12:30 UTC by Faust1-2was-Aneo

Used BehaviorSubjects to indicates the state of grafana and seq in the GUI instead of private booleans.

2022-11-10 14:51 UTC, esoubiran-aneo requested changes

2022-11-10 14:51 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.ts
> +    this.settingsService.seqSubject$.subscribe((v) => (this.isSeqUp = v));
Je pense que cette ligne n'est plus utile

2022-11-10 14:51 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages.component.html
> +      <div
Tu as la possibilité de ne faire le async qu'une fois (sur chacun des services) pour éviter la redondance entre cette ligne et la ligne 35 ou 44.

Je te laisse lire ça dans cette article : https://medium.com/@yurykatkov/how-to-avoid-multiple-async-pipes-in-angular-ff0d51a8d368

2022-11-10 14:51 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages.component.html
> +          (settingsService.seqSubject$ | async) ||
Tu peux éviter une double souscription en utilisant un petit trick sur le *ngIf. (à lire juste là https://medium.com/@yurykatkov/how-to-avoid-multiple-async-pipes-in-angular-ff0d51a8d368)

2022-11-10 21:14 UTC, Barbapapazes commented on apps/app/src/app/pages/pages.component.html
> +      <div
Tu peux utiliser un ng-contaner piur éviter d'avoir une div vide !

2022-11-14 09:07 UTC, maurelleAneo requested changes

2022-11-14 09:07 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +    [isSeqUp]="(settingsService.seqSubject$ | async) || false"
Pourquoi rajouter un `|| false` ?

2022-11-14 09:07 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.html
> +    [isSeqUp]="(settingsService.seqSubject$ | async) || false"
Même question ici

2022-11-16 09:46 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +    [isSeqUp]="(settingsService.seqSubject$ | async) || false"
`| async` peut renvoyer `<type> | undefined` et il faut du coup lui fournir une valeur par défaut.

2022-11-21 17:09 UTC, maurelleAneo requested changes

2022-11-21 17:09 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/dashboard/dashboard.component.html
> +    [isSeqUp]="(settingsService.seqSubject$ | async) || false"
C'est dans le composant `app-pages-dashboard-applications-errors-list` qu'il faut gérer ça en indiquant que isSeqUp peut être undefined et par défaut être égal à false (ce qui est partiellement déjà fait, il suffit juste de rajouter que ça peut être undefined). Le jour où la valeur par défaut devra être set à true alors là ce sera utile de mettre un `|| true`. Mais en général c'est faux donc autant le gérer de manière plus élégante

2022-11-22 09:57 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.ts
> +  @Input() isSeqUp: boolean | null = false;
Attention à ne pas faire de confusion ici : on parlait d'une possibilité de boolean | undefined ou boolean | null ou alors boolean | null | undefined ?

2022-11-22 10:04 UTC, Faust1-2was-Aneo commented on apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.ts
> +  @Input() isSeqUp: boolean | null = false;
Il y a bien eu une confusion, le `| async` renvoit en fait `<type> | null` et **pas** `<type>| undefined`

2022-11-22 10:20 UTC, maurelleAneo approved these changes

2022-11-22 11:41 UTC, esoubiran-aneo approved these changes

2022-11-22 11:41 UTC, merged