feat: handle custom columns
aneoconsulting/ArmoniK.Admin.GUI pull request #304
Opened 2022-11-15 15:21 UTC by esoubiran-aneo

2022-11-22 15:38 UTC, esoubiran-aneo commented
Voir si l'API est mergée pour mettre en review

2022-11-23 12:55 UTC, esoubiran-aneo commented
Passer en component dans un shared

2022-11-28 11:28 UTC, maurelleAneo requested changes

2022-11-28 11:28 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +      'custom_columns',
Si ce fonctionnement est étendu sur les autres pages, tu ne devrais pas enregistrer tes colonnes dans une partie "session-list" du localstorage  ? Ou alors ces colonnes sont les mêmes partout

2022-11-28 11:28 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +  public findCustomColumnValue(session: SessionSummary, key: string) {
Manque type de retour

2022-11-28 11:28 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
> +        (addColumnChange)="addColumn($event)"
Pourquoi ce n'est pas le composant `app-custom-columns-manager` qui fait la gestion des colonnes ?

2022-11-28 11:28 UTC, maurelleAneo commented on apps/app/src/app/shared/components/custom-columns-manager/custom-columns-manager.component.ts
> +  private _modalAddColumnOpened: Subject<boolean> = new Subject<boolean>();
Pourquoi tu fais un observable ici ? Un simple boolean suffit

2022-11-28 11:28 UTC, maurelleAneo commented on apps/app/src/app/shared/components/custom-columns-manager/custom-columns-manager.component.ts
> +  /** Manage columns */
Pourquoi tu fais un observable ici ? Un simple boolean suffit

2022-12-05 08:06 UTC, maurelleAneo reviewed
Il restera un commentaire à traiter

2022-12-05 09:02 UTC, esoubiran-aneo commented
> Il restera un commentaire à traiter

Ah mes commentaires ne se sont pas envoyé !

2022-12-19 10:44 UTC, esoubiran-aneo commented
move to #345

2022-12-19 10:44 UTC, closed without merging