refactor: history
aneoconsulting/ArmoniK.Admin.GUI pull request #307
Opened 2022-11-16 10:38 UTC by esoubiran-aneo

2022-11-17 11:18 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/history.service.ts
> +    console.log(history);
Muse be removed

2022-11-29 09:02 UTC, GunaDinesh submitted a review, later dismissed

2022-11-29 09:12 UTC, maurelleAneo requested changes

2022-11-29 09:12 UTC, maurelleAneo commented on apps/app/src/app/core/services/history.service.ts
> +  private _historySubject = new BehaviorSubject<Set<string>>(this._history);
Attention ici même remarque que sur le service des favoris

2022-11-29 09:12 UTC, maurelleAneo commented on apps/app/src/app/core/services/history.service.spec.ts
> +  it('should store history in local storage when subscribe', () => {
Ce test sert à quoi exactement ?

2022-11-29 09:51 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/history.service.ts
> +  private _historySubject = new BehaviorSubject<Set<string>>(this._history);
Yes, je change ça !

2022-11-29 09:53 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/history.service.spec.ts
> +  it('should store history in local storage when subscribe', () => {
Je l'ai mis à jour mais il permet de s'assurer que l'élément est bien store lors d'un ajout !

2022-11-29 09:57 UTC, maurelleAneo approved these changes

2022-11-29 10:11 UTC, merged