refactor: auto refresh dropdown
aneoconsulting/ArmoniK.Admin.GUI pull request #310
Opened 2022-11-17 10:10 UTC by esoubiran-aneo

2022-11-21 09:23 UTC, maurelleAneo requested changes

2022-11-21 09:23 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
> +export class AutoRefreshDropdownComponent implements OnInit, OnDestroy {
Tu devrais placer ce composant dans le dossier : app/shared/components

2022-11-21 10:09 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
> +export class AutoRefreshDropdownComponent implements OnInit, OnDestroy {
mais ça veut dire que tous les modules qui utilise `shared` vont devoir importer un composant qu'il n'utilisa pas forcément ?

2022-11-22 09:22 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
> +export class AutoRefreshDropdownComponent implements OnInit, OnDestroy {
Ce n'est pas grave, au moins dès que tu en aura besoin tu n'aura pas à te poser de question de savoir si tu dois le sortir d'un niveau d'arboresence ou non. De ce que je viens de checker, l'arborescence est assez compliqué puisque tu imbriques en fonction d'où se trouvent tes besoins. Mais si cela change tu vas devoir casser des choses. En général ce que l'on fait (sur mes projets en tout cas) c'est un dossier par module dans `/pages`, correspondant en général à une page Web distincte. Mais à partir du moment où un module/composant commence à être partagé alors on le transforme en module (si c'était un simple composant) que l'on place dans un dossier shared.

2022-11-22 09:25 UTC, maurelleAneo commented on apps/app/src/app/pages/pages/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
> +export class AutoRefreshDropdownComponent implements OnInit, OnDestroy {
Et si tu as besoin de créer des composant carrément globaux (ex barre de navigation, etc.. qu tu retrouves dans le layout général) tu peux même te faire un lib `/ui` qui sera importé par ton `app.module`

2022-11-23 09:08 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
> +export class AutoRefreshDropdownComponent implements OnInit, OnDestroy {
Okkk, je vois le truc, je vais faire ça!

2022-11-23 09:15 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
> +export class AutoRefreshDropdownComponent implements OnInit, OnDestroy {
Il va falloir que je fasse une PR pour clean un peu le repos et les composants parce qu'il y en a de partout !

2022-11-28 11:36 UTC, maurelleAneo approved these changes

2022-11-28 11:36 UTC, merged