chore: update package manager
aneoconsulting/ArmoniK.Admin.GUI pull request #312
Opened 2022-11-22 09:16 UTC by esoubiran-aneo

2022-11-22 17:34 UTC, maurelleAneo requested changes

2022-11-22 17:34 UTC, maurelleAneo commented on .github/workflows/cd-docker.yml
> +        run: yarn proto:generate
`yarn run` ?

2022-11-22 17:34 UTC, maurelleAneo commented on .github/workflows/ci.yaml
> +        run: yarn proto:generate
Tu ne remplaces pas tous les npm run par `yarn run` ?

2022-11-22 17:34 UTC, maurelleAneo commented on .husky/pre-commit
> +yarn pre-commit
`yarn run` ?

2022-11-22 17:34 UTC, maurelleAneo commented on README.md
> +yarn start
Tu ne remplaces pas tous les `npm run` par `yarn run` ?

2022-11-22 17:34 UTC, maurelleAneo commented on README.md
>  ### Install Nx globally (Optional)
Tu installes nx avec npm ?

2022-11-22 17:34 UTC, maurelleAneo commented on README.md
>  ### App
Dans l'analyse de map il reste un npm

2022-11-22 17:34 UTC, maurelleAneo commented on api.Dockerfile
> +RUN yarn
Tu mixes npm et yarn dans ce fichier ?

2022-11-22 17:34 UTC, maurelleAneo commented on app.Dockerfile
> +RUN yarn
Pareil ici ?

2022-11-22 23:19 UTC, esoubiran-aneo commented on .github/workflows/ci.yaml
> +        run: yarn proto:generate
Nan, yarn n'a pas besoin du keyword `run` !

2022-11-22 23:20 UTC, esoubiran-aneo commented on README.md
>  ### Install Nx globally (Optional)
yes parce qu'en global, ça n'a pas d'importance mais il faudrait que je retravaille cette partie de la documentation parce qu'en réalité, ça n'a pas de sens de l'installer en local.

2022-11-22 23:22 UTC, esoubiran-aneo commented on api.Dockerfile
> +RUN yarn
yes parce que c'est une install local mais je peux essayer avec yarn de la faire en global aussi,c 'est vrai. sur la finalité, ça ne change pas grand chose.

2022-11-23 08:55 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
> +        run: yarn proto:generate
Il n'y en a pas forcément besoin.

https://yarnpkg.com/cli/run#examples

2022-11-23 08:58 UTC, esoubiran-aneo commented on api.Dockerfile
> +RUN yarn
Yarn est directement dans le projet dans le dossier `.yarn`. Du coup, ça ne permet pas d'installer des modules au global.

2022-11-23 09:44 UTC, esoubiran-aneo commented
Change this `node-modules-${{ hashFiles('package-lock.json') }}`

2022-11-28 11:37 UTC, maurelleAneo approved these changes

2022-11-28 11:38 UTC, merged