Feat datagrid filters
aneoconsulting/ArmoniK.Admin.GUI pull request #313
Opened 2022-11-25 11:05 UTC by Faust1-2was-Aneo

Created filters for the datagrids :
- date filters
- status filters
- id filters

2022-11-25 19:10 UTC, esoubiran-aneo requested changes

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +        return value !== null && !isNaN(Number(value))
Tu peux factoriser le code sur le value en le rendant `Number`.

```js
if(!value) {
  return null
}

const param = Number(value)

if(isNaN(param)) {
  return null
}

return new Date(param)
```

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +        return value !== null && !isNaN(Number(value))
Cela permet de garder un code claire et facilement lisible.

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +    return jsonDate !== '' ? new Date(jsonDate) : null;
Evite l'utilisation de la négation dans les opérateurs ternaires. Cela les rend difficile à lire.

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +    console.log(params);
Il est en trop celui là !

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-list-filter/sessions-list-filter.component.html
> +    (clrDateChange)="onChange()"
```suggestion
    (clrDateChange)="onDateChange()"
```

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-list-filter/sessions-list-filter.component.html
> +    (clrDateChange)="onChange()"
```suggestion
    (clrDateChange)="onDateChange()"
```

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-list-filter/sessions-list-filter.component.html
> +    (clrDateChange)="onChange()"
Cela permet d'ajouter plus de clarté au code et à sa lecture !

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-list-filter/sessions-list-filter.component.ts
> +  get value() {
`value` fait parti de l'interface ?

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-list-filter/sessions-list-filter.component.ts
> +  get property() {
N'oublie pas d'ajouter les types des retours sur l'ensemble des fonctions !

2022-11-25 19:10 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-status-filter/sessions-status-filter.component.html
> +    <option *ngFor="let item of status" [value]="item.value">
Il faut ajouter le `trackBy` ! https://angular.io/api/core/TrackByFunction

Cela permet à angular de ne pas re-rendre des composants qui n'ont pas changé.

2022-11-25 19:14 UTC, esoubiran-aneo requested changes

2022-11-25 19:14 UTC, esoubiran-aneo commented on apps/app/src/app/shared/services/states.service.ts
> +  setFilterValue(stateName: string, key: string, value: string) {
Il y a une sauvegarder du dernier état dans le localstorage ?

2022-11-28 08:47 UTC, Faust1-2was-Aneo commented on apps/app/src/app/shared/services/states.service.ts
> +  setFilterValue(stateName: string, key: string, value: string) {
La fonction n'est plus utilisée, j'ai oublié de la retirer du code (je vais le faire).
Je l'avais créée avant de comprendre comment fonctionnait les filtres.

A la base, dans session-component (qui n'est plus utilisé), la fonction `onNextSessions` s'occupait déjà de sauvegarder le state, je n'ai pas trouvé utile de faire une sauvegarde, sachant que les filtres allaient être déjà sauvegardés.

2022-11-28 08:51 UTC, Faust1-2was-Aneo commented on apps/app/src/app/shared/filters/sessions-list-filter/sessions-list-filter.component.ts
> +  get value() {
`value` n'est pas implémenté de base dans l'interface.
Mais tout comme property, elle est utilisée pour récupérer la valeur du filtre dans `grpc-pager.services.ts > _createFilters`.

2022-11-28 09:06 UTC, Faust1-2was-Aneo commented on apps/app/src/app/core/services/grpc/grpc-pager.service.ts
> -    const params = new Map<string, string | number>();
Certainement une erreur de ma part, j'ai beaucoup touché à l'objet.

2022-11-28 09:11 UTC, Faust1-2was-Aneo commented on apps/app/src/app/core/services/grpc/grpc-pager.service.ts
> +    params: Map<string, string | number | SessionFilter>
Oubli de ma part, `SessionFilter` n'est plus utilisé pour créer les filtres.

2022-11-28 12:14 UTC, Faust1-2was-Aneo commented on apps/app/src/app/core/services/pager.service.ts
> +      if (filter.value !== '') {
le `state` de `session.component` contient uniquement les filtres actifs qu'il implémente.

Si le filtre est supprimé, le component passera en inactif, et il ne sera pas vu comme propriété du `state`. Le filtre ne sera pas ajouté à la query, donc il n'y aura pas de soucis de type string vide.

2022-11-28 15:11 UTC, esoubiran-aneo commented
@Faust1-2was-Aneo Il faut faire un petit merge !

2022-11-28 22:14 UTC, esoubiran-aneo requested changes

2022-11-28 22:35 UTC, esoubiran-aneo requested changes

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +    this._state.filters = undefined;
On va préférer `null` !

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +    this._state.filters = undefined;
https://www.javatpoint.com/null-vs-undefined

> 4. | Null indicates the absence of a value for a variable. | Undefined indicates the absence of the variable itself.

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions/sessions.component.ts
> +  getDateFilterValue(key: string): Date | null {
C'est un reste d'une modification ?

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.html
> +  <label>{{ 'pages.sessions-list.filters.date.before' | translate }}</label>
Changer le path des traductions pour avoir un truc plus générique maintenant que c'est dans shared

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.spec.ts
> +    component.changes.emit = jasmine.createSpy();
`emit `est un observable ! Donc tu peux t'abonner et d'assurer sur tu reçois bien ce que tu veux !

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.spec.ts
> +  it('should have null dates', () => {
à l'initialisation ? Il faut ajouter un peu de contexte !

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.spec.ts
> +    it('should be active when a "after date" is picked', () => {
Il ne faut pas ajouter un cas où les 2 sont set ?

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.ts
> +  changes = new EventEmitter<boolean>(false);
Il manque le flag @Output

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.ts
> +  changes = new EventEmitter<boolean>(false);
https://angular.io/guide/inputs-outputs#sending-data-to-a-parent-component

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.ts
> +    return JSON.stringify({
à changer du coup pour sortir un object et ne pas avoir cette étrange conversion interne !

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.ts
> +    this.changes.emit(false);
Pourquoi c'est false ?

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/id-filter/id-filter.component.ts
> +  changes = new EventEmitter<boolean>(false);
Il manque le output là aussi !

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/id-filter/id-filter.component.ts
> +  ngOnInit(): void {
Je n'ai pas de solutions mais je pense qu'il y a mieux à faire.

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-status-filter/sessions-status-filter.component.ts
> +  changes = new EventEmitter<boolean>(false);
Manque l'output

2022-11-28 22:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-status-filter/sessions-status-filter.component.ts
> +    this.selectedValue = 0;
Une const pourrait à la lecture d'autant que c'est un peu une magic value utilisé à au moins 2 reprises dans le fichier !

2022-11-29 09:55 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +      filter.createdBefore = new Timestamp(timestamp);
D'après le typage

```ts
    interface AsObject {
        seconds?: string;
        nanos?: number;
    }
```

2022-11-29 09:56 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +      filter.createdBefore = new Timestamp(timestamp);
Mais oui, il semble que seconds soit une string !

2022-11-29 15:18 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +    const filterValue = this.createFilterObject(params);
```suggestion
    const filter = this.createFilter(params);
```

2022-11-29 15:18 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +      filter: {
```suggestion
      filter: filter
```

2022-11-29 15:18 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +  createFilterObject(
```suggestion
  createFilter(
```

2022-11-29 15:19 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +        ...filterValue,
```suggestion
```

2022-11-29 15:19 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +      },
```suggestion
```

2022-11-29 15:20 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +    const filterValue = this.createFilterObject(params);
```suggestion
    const filterValue = this.createFilter(params);
```

2022-11-29 15:20 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +import { SessionPageFilter } from '../../types/session-string-filter.type';
Il faut renommer le nom du type pour qu'il existe une correspondance avec le nom du fichier

2022-11-29 15:22 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +    const paramsFilter = params as SessionPageFilter; // Transform the params in order to have all required properties
Nan, ça ce n'est pas possible de faire un cast de ce type.

Je pense que l'utilisation d'un generic dans params avec une clé filter de type T et dans le cas des sessions T est le type des filtres des sessions mais le code n'est vraiment pas clair avec ça

2022-11-29 15:23 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +        seconds: (paramsFilter.createdAtBefore / 1000).toString(),
Tu peux faire une fonction pour faire ça !

2022-11-29 15:24 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
> +    const paramsFilter = params as SessionPageFilter; // Transform the params in order to have all required properties
Un cast comme celui-ci serait possible si GrpcParams et SessionPageFilter avoir un point commun mais de ce que je comprends là, ce n'est pas le cas.

2022-11-29 15:24 UTC, esoubiran-aneo commented on apps/app/src/app/core/services/pager.service.ts
> +      if (filter.value !== '') {
Tu peux retirer les changements ?

2022-11-29 15:26 UTC, esoubiran-aneo commented on apps/app/src/app/core/types/session-filter.type.ts
> +export type SessionFilter = {
ça me semble trop similaire avec `SessionPageFilter`

2022-11-29 15:26 UTC, esoubiran-aneo commented on apps/app/src/app/core/types/session-filter.type.ts
> +export type SessionFilter = {
Il faut trouver un moyen pour n'en garder qu'un

2022-11-29 15:27 UTC, esoubiran-aneo commented on apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
> +   * @returns Observable<number>
```suggestion
   * @returns Observable<string>
```

2022-11-29 15:29 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.ts
> +  @Output() changes = new EventEmitter();
tu peux quand même le type avec never (ou void, j'ai un doute)

2022-11-29 15:30 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/id-filter/id-filter.component.ts
> +  @Output() changes = new EventEmitter();
Tu peux le typer.

2022-11-29 15:31 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/id-filter/id-filter.component.ts
> +      .asObservable()
Crée une clé interne qui te servira d'observable, ça rendre les intentions plus claires !

2022-11-29 15:32 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/id-filter/id-filter.component.ts
> +    this.inputChange = this.inputChangeSubject
```suggestion
    this.inputChange = this._inputChange$
```

2022-11-29 15:34 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/id-filter/id-filter.component.ts
> +    this.inputChange = this.inputChangeSubject
Et il faut trouver un autre nom à inputChange (un truc comme input devrait suffire parce que le `change` dans angular, c'est pour le 2 ways data binding.

Crée une clé interne qui te servira d'observable, ça rendre les intentions plus claires !

2022-11-29 15:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-status-filter/sessions-status-filter.component.ts
> +  @Output() changes = new EventEmitter();
Tu peux typer (pour qu'on comprenne que ce n'est pas un oubli mais volontaire de ne rien émettre)

2022-12-13 12:25 UTC, esoubiran-aneo requested changes
3 petits choses et ça sera parfait ! 👌

2022-12-13 12:25 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/index.ts
> +export { SessionsStatusFilterComponent } from './sessions-status-filter/sessions-status-filter.component';
Tu peux intégrer le dossier `filters` dans `feature` parce que ça reste des composants

2022-12-13 12:25 UTC, esoubiran-aneo commented on apps/app/src/app/shared/filters/sessions-status-filter/sessions-status-filter.component.html
> +  <label>{{ 'pages.sessions-list.filters.status.title' | translate }}</label>
Pour toutes les traductions, tu peux les mettre dans le namespace 'pages.components' puisque ce n'est plus uniquement pour les sessions.

2022-12-13 12:25 UTC, esoubiran-aneo commented on libs/sessions/data-access/src/lib/services/grpc-sessions.service.ts
> +      if (key === 'page') {
Un petit `switch` permettrait une meilleure lisibilité

2022-12-13 12:27 UTC, esoubiran-aneo commented on libs/sessions/data-access/src/lib/services/grpc-sessions.service.ts
> +  private createTimeFilter(value: number): TimeFilter {
Les fonctions `private`, on a pour habitude de les préfixer avec un `_`. ça vient du fait que le `#` n'existait pas il y a quelques années et c'est une habitude qui s'est gardé comme norme dans Angular.

2022-12-13 14:11 UTC, maurelleAneo requested changes

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.spec.ts
> +  it('should emit when the filter is cleared', () => {
Pareil ici

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/date-filter/date-filter.component.spec.ts
> +  it('should send an object with beforeDate null when only afterDate is picked', () => {
Même question ici

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/index.ts
> +export { SessionsStatusFilterComponent } from './sessions-status-filter/sessions-status-filter.component';
Je pense qu'il faudrait plutôt faire une archi de ce style : `shared/features/filters/...`
Qu'en penses-tu ? Cela permettra d'intégrer d'autres features plus tard au besoin

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/app/tasks/feature/tasks-list/tasks-list.page.html
> +                ].includes(task.status || 0),
Pourquoi y a-t-il des `|| 0` partout ?

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/assets/i18n/en.json
> +        "before-date": "Will display data with a date stricly inferior than indicated.",
strictly

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/assets/i18n/en.json
> +        "after-date": "Will display data with a date stricly superior than indicated."
strictly

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/assets/i18n/en.json
> +      "no-filter-available": "No filter available",
Attention, le fichier de traduction est en snake case => on utilise des `_` pour les clés et non des `-`

2022-12-13 14:11 UTC, maurelleAneo commented on apps/app/src/app/shared/filters/sessions-status-filter/sessions-status-filter.component.spec.ts
> +  it('should emit an Event when selection change', () => {
Pareil ici, ne peux-tu pas spy la fonction emit ?

2022-12-15 15:12 UTC, maurelleAneo requested changes

2022-12-15 15:12 UTC, maurelleAneo commented on apps/app/src/app/sessions/feature/sessions-list/sessions-list.page.html
> +        {{ 'pages.components.filters.clear-all-filters' | translate }}
Cette traductions se trouvant dans sessions-list, il faut que sa clé fasse partie de `sessions-list` dans le fichier de traduction (même si cela amène à des doublons)

2022-12-15 15:12 UTC, maurelleAneo commented on apps/app/src/app/shared/feature/filters/sessions-status-filter/sessions-status-filter.component.html
> +  <label>{{ 'pages.components.filters.status-title' | translate }}</label>
pages.components.filters.status **.** title

2022-12-15 15:12 UTC, maurelleAneo commented on apps/app/src/assets/i18n/en.json
>        "filters": {
Les status de sessions doivent faire partie de la traduction des filtres car sont utilisés dans les filtres

2022-12-15 15:12 UTC, maurelleAneo commented on apps/app/src/app/shared/feature/filters/sessions-status-filter/sessions-status-filter.component.html
> +      {{ 'pages.sessions-list.filters.' + item.label | translate }}
On est dans un composant de pages.components -> on utilise la traduction de pages.component

2023-01-02 10:23 UTC, maurelleAneo requested changes

2023-01-09 08:46 UTC, maurelleAneo approved these changes

2023-01-30 09:55 UTC, esoubiran-aneo requested changes

2023-01-30 09:55 UTC, esoubiran-aneo commented on apps/app/src/app/sessions/feature/sessions-list/sessions-list.page.html
> +          [placeholder]="applicationNamePlaceHolder"
Changer avec https://angular.io/guide/i18n-common-prepare#i18n-title-example

2023-01-31 11:08 UTC, esoubiran-aneo approved these changes

2023-01-31 11:08 UTC, merged