Feat datagrid results filters
aneoconsulting/ArmoniK.Admin.GUI pull request #334
Opened 2022-12-14 08:45 UTC by Faust1-2was-Aneo

Add result filter to Admin GUI.

Will be able to filter through :

- The result's name.
- The result's taskId.
- The result's SessionId.
- The result's status (only one at a time).
- The result's creation date.

2022-12-14 12:40 UTC, esoubiran-aneo requested changes
Rendre le filtre plus générique

2022-12-14 17:56 UTC, Barbapapazes reviewed
À quoi ça correspond tout ce qui est commenté ?

Sinon c'est parfait la généralisation du filtre.

2022-12-19 15:41 UTC, esoubiran-aneo requested changes

2022-12-19 15:46 UTC, esoubiran-aneo commented on apps/app/src/app/results/feature/results-list/results-list.page.html
> +          [inputValue]="(nameFilter$ | async) || ''"
ça ne semble pas possible vu le type du pipe 

```ts
transform<T>(obj: Observable<T> | Subscribable<T> | Promise<T>): T | null;
```

2022-12-19 15:48 UTC, esoubiran-aneo commented on apps/app/src/app/results/feature/results-list/results-list.page.html
> +          [inputValue]="(nameFilter$ | async) || ''"
ça veut dire qu'il faut gérer autrement la chose.

Dans le filtre, il faut que le type d'input soit `string | null`. Ensuite, il faut ajuster les fonctions internes au filtre pour gérer correctement si l'input est null ou s'il est une string.

Dans le même temps, ça veut dire qu'on n'a forcément besoin de retirer les valeurs null vu que c'est au filtres de traiter.

https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/334/files#diff-b4063fd7c979bd9f295a462c9f61fa69019739e6a5c07d7f8227387c49225eebR219

2022-12-19 15:50 UTC, Faust1-2was-Aneo commented on apps/app/src/app/results/feature/results-list/results-list.page.html
> +          [inputValue]="(nameFilter$ | async) || ''"
Ok, je pense qu'il va falloir faire ça avec tous les filtres, je vais ouvrir une PR pour les modifier, et on pourra ensuite se débarrasser des pipes.

2022-12-20 08:57 UTC, esoubiran-aneo approved these changes
Je la merge mais je pense que `queryDateParam$` et `queryStringParam$` pourront faire l'objet d'un service parce que ça va être réutilisé !

2022-12-20 08:58 UTC, merged