Created combobox-filter component
aneoconsulting/ArmoniK.Admin.GUI pull request #339
Opened 2022-12-15 09:55 UTC by Faust1-2was-Aneo

2022-12-15 10:12 UTC, esoubiran-aneo requested changes

2022-12-15 10:12 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/index.ts
> +export {} from './combobox-filter/combobox-filter.component';
Il manque l'export du coup !

2022-12-15 16:42 UTC, Barbapapazes submitted a review, later dismissed

2022-12-15 20:12 UTC, esoubiran-aneo approved these changes

2022-12-16 13:50 UTC, esoubiran-aneo commented
@Faust1-2was-Aneo conflit ! Ping moi dès que c'est fait pour que je la merge et qu'on puisse se faire la dernière !

2022-12-16 17:43 UTC, esoubiran-aneo approved these changes

2022-12-16 17:43 UTC, merged