feat: Created id-filter component
aneoconsulting/ArmoniK.Admin.GUI pull request #340
Opened 2022-12-15 10:15 UTC by Faust1-2was-Aneo

2022-12-15 10:35 UTC, esoubiran-aneo requested changes
à verifier quand même que tout fonctionne.

Faire la différence entre le sujet et l'observable se fait finalement grâce au `$` du coup, pas besoin d'écrire `Subject` (et oui, je vais aussi devoir en changer pas mal dans le reste du code !)

2022-12-15 10:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.ts
> +  subscription: Subscription = new Subscription();
```suggestion
  subscription: Subscription | null = null;
```

ça permet d'éviter d'avoir à instancier un object alors que tu sais très bien qu'il va être remplacer 3 lignes plus tard

2022-12-15 10:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.ts
> +    this.subscription.unsubscribe();
```suggestion
    this.subscription?.unsubscribe();
```

2022-12-15 10:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.ts
> +  inputSubject = new Subject<string>();
```suggestion
  public input = new Subject<string>();
  private _input$ = this.input.asObservable();
```

2022-12-15 10:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.ts
> +    const input$ = this.inputSubject.asObservable();
```suggestion
```

2022-12-15 10:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.ts
> +    this.subscription = input$
```suggestion
    this.subscription = this._input$
```

2022-12-15 10:35 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.spec.ts
> +    expect(component.inputSubject).toBeDefined();
```suggestion
    expect(component.input).toBeDefined();
```

2022-12-15 10:38 UTC, esoubiran-aneo requested changes
Il manque les traductiosn

2022-12-15 16:41 UTC, Barbapapazes submitted a review, later dismissed

2022-12-15 20:11 UTC, esoubiran-aneo approved these changes

2022-12-15 20:11 UTC, esoubiran-aneo commented
@Faust1-2was-Aneo conflit à résoudre !

2022-12-16 13:49 UTC, esoubiran-aneo approved these changes

2022-12-16 13:49 UTC, merged