Fix: move urlToGrpcParams to Grpc_pager service
aneoconsulting/ArmoniK.Admin.GUI pull request #347
Opened 2022-12-19 13:31 UTC by Faust1-2was-Aneo

2022-12-28 16:02 UTC, esoubiran-aneo requested changes

2022-12-28 16:02 UTC, esoubiran-aneo commented on libs/shared/data-access/src/lib/types/global-filter.type.ts
> +export interface GlobalFilter {
Est-ce que tu peux m'expliquer le principe de ce type et la manière dont il est utilisé par le reste du code ?

2022-12-28 16:21 UTC, Faust1-2was-Aneo commented on libs/shared/data-access/src/lib/types/global-filter.type.ts
> +export interface GlobalFilter {
Chaque service a un filtre différent.
Or je n'ai pas réussi à passer en paramètre de la fonction `_createGrpcParamsFilters` un filtre pouvant être de chacun de ces types.
Le problème était qu'en faisant ça, aucun attribut de chaque filtre n'était reconnu.

J'ai donc créé le l'interface `GlobalFilter` pour pouvoir régler ce problème en ayant un filtre général possédant toutes les informations nécessaire à chaque filtre.

2022-12-29 13:05 UTC, esoubiran-aneo commented on libs/shared/data-access/src/lib/types/global-filter.type.ts
> +export interface GlobalFilter {
Okkk je vois, je vais me pencher dessus parce que ça ne me satifait pas trop en terme d'évolutivité et de clarté du code.

2022-12-29 13:09 UTC, Faust1-2was-Aneo commented on libs/shared/data-access/src/lib/types/global-filter.type.ts
> +export interface GlobalFilter {
Je suis d'accord.

Je suis repassé dessus pour essayer de le rendre plus intuitif mais ça reste laborieux. Plutôt que d'utiliser les strings, je donne plutôt les `Filters` définis par les protos. C'est un peu plus lourd mais c'est plus lisible et ça permet de pas envoyer de données inutiles dans les requêtes.

2023-01-03 17:37 UTC, esoubiran-aneo commented
@Faust1-2was-Aneo, je pense la suite de cette branche ! Je pense avoir une bonne piste pour simplifier le code.

2023-01-18 15:46 UTC, Faust1-2was-Aneo commented
Still have to fix date filters value in URL.

2023-02-08 15:00 UTC, esoubiran-aneo approved these changes

2023-02-08 15:00 UTC, merged