feat: datagrid applications filters
aneoconsulting/ArmoniK.Admin.GUI pull request #348
Opened 2022-12-19 15:36 UTC by Faust1-2was-Aneo

2022-12-28 09:23 UTC, esoubiran-aneo requested changes

2022-12-28 09:23 UTC, esoubiran-aneo commented on apps/app/src/app/applications/feature/applications-list/applications-list.page.ts
> +  public queryStringParam$(param: string): Observable<string> {
Tu l'as déplacé dans le `settingsService` !

2022-12-28 16:00 UTC, esoubiran-aneo requested changes

2022-12-28 16:00 UTC, esoubiran-aneo commented on apps/app/src/app/applications/feature/applications-list/applications-list.page.html
> +          [name]="'service'"
```suggestion
          name="service"
```

2022-12-28 16:10 UTC, Faust1-2was-Aneo commented on apps/app/src/app/applications/feature/applications-list/applications-list.page.html
> +          [name]="'name'"
Plutôt que d'utiliser une variable supplémentaire, j'ai décidé de passer directement le string de cette manière aux filtres, qui en a besoin.

2022-12-29 13:04 UTC, esoubiran-aneo commented on apps/app/src/app/applications/feature/applications-list/applications-list.page.html
> +          [name]="'name'"
Yes mais tu n'as pas forcément besoin de faire un ajout via avec `[]` vu que c'est juste une string

https://angular.io/api/core/Input

2023-01-09 10:10 UTC, esoubiran-aneo requested changes

2023-01-09 10:10 UTC, esoubiran-aneo commented on apps/app/src/app/applications/feature/applications-list/applications-list.page.html
> +          [inputValue]=" nameFilter$ | async"
Il ne faudrait pas les rendre statique, comme tu as pu faire dans #380 ?

2023-01-09 10:11 UTC, Faust1-2was-Aneo commented on apps/app/src/app/applications/feature/applications-list/applications-list.page.html
> +          [inputValue]=" nameFilter$ | async"
Oui, je n'y ai pas touché depuis un moment, il est temps de mettre la branche à jour

2023-01-19 15:53 UTC, Faust1-2was-Aneo commented
The filters are currently using the `urlToGrpcParams` function. Can be changed after or in #347.

2023-02-02 09:46 UTC, esoubiran-aneo approved these changes

2023-02-02 09:46 UTC, merged