edit cd-docker.yml and ci.yaml
aneoconsulting/ArmoniK.Admin.GUI pull request #360
Opened 2022-12-22 15:40 UTC by Faust1-2was-Aneo

Need advices.

2022-12-22 15:41 UTC, Faust1-2was-Aneo commented
The modifications are commented for now.

2022-12-22 16:19 UTC, Barbapapazes commented on .github/workflows/cd-docker.yml
> +      #     key: ${{ runner.os }}-protobuf
Need to use a hash of ArmoniK.Api submodule

2022-12-27 08:54 UTC, esoubiran-aneo requested changes
Tu peux ne pas commenter tes modifications. Cela ne changera la pipeline que sur la branche et non sur l'intégralité du repo.

2022-12-27 10:02 UTC, esoubiran-aneo requested changes

2022-12-27 10:02 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
> +          path: libs/shared/data-access/src/lib/proto/generated
On ne peut pas faire ça puisque le contenu d'un fichier peut changer sans que ça n'ai d'impact sur le hash mais dans le même temps, j'ai bien l'impression qu'il n'y a pas de fichers pour la version.

2022-12-27 10:03 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
> +          path: libs/shared/data-access/src/lib/proto/generated
Je pense que ça va demander d'ajouter un version.txt avec le numéro de version dans le repo @aneojgurhem qui devra être mis à jour avant de faire une release.

2022-12-27 10:05 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
> +          path: libs/shared/data-access/src/lib/proto/generated
Oui ça me gênait d'utiliser un tel fichier pour le hash.
A ce niveau là il faudrait bien ça sur l'autre repo.

2022-12-27 10:07 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
> +          path: libs/shared/data-access/src/lib/proto/generated
et hasher les fichiers d'un dossier, ça ne semble pas fonctionner https://github.com/nektos/act/issues/1012

2022-12-27 10:10 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
> +          path: libs/shared/data-access/src/lib/proto/generated
Ou @Faust1-2was-Aneo, tu peux utiliser une regex pour pour matcher l'ensemble des protos files et générer le hash à partir de ça 

https://github.com/actions/runner/blob/main/src/Misc/expressionFunc/hashFiles/src/hashFiles.ts

2022-12-27 10:14 UTC, esoubiran-aneo requested changes

2022-12-27 10:14 UTC, esoubiran-aneo commented on .github/workflows/ci.yaml
>        - name: Install Protoc
peut être supprimé puisque forcément, de part la dépendance des jobs, les proto auront été généré

2022-12-27 10:14 UTC, esoubiran-aneo commented on .github/workflows/ci.yaml
>        - name: Build proto
à supprimer

2022-12-27 10:14 UTC, esoubiran-aneo commented on .github/workflows/ci.yaml
> +        if: steps.proto-cache.outputs.cache-hit != 'true'
peut être supprimé

2022-12-27 10:14 UTC, esoubiran-aneo commented on .github/workflows/ci.yaml
>        - name: Build proto
peut être suppirmé

2022-12-27 14:59 UTC, esoubiran-aneo approved these changes
Ça me semble bon. On verra par la suite si on rencontre des erreurs.

2022-12-27 14:59 UTC, merged