Edit favorites
aneoconsulting/ArmoniK.Admin.GUI pull request #403
Opened 2023-01-10 14:19 UTC by Faust1-2was-Aneo

### 🔗 Linked issue
&fix #399 
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Reworked favorites services due to a bug.
When having a composed url like `.../users/me`, the second `/` would be serialized into `%2F`.

Fix: pass a string list to the routerLink instead of just a string in case of a composed url.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-01-10 14:46 UTC, esoubiran-aneo commented on apps/app/src/app/shared/util/services/favorites.service.ts
> +            url: root.children['primary'].segments.toString(),
Si je comprends bien, c'est l'URL c'est `segment1,segment2,segment3` ?

2023-01-10 14:49 UTC, esoubiran-aneo commented on apps/app/src/app/shared/util/services/favorites.service.ts
> +            url: root.children['primary'].segments.toString(),
On doit pouvoir faire plus simple en retournant un tableau qui contient tous les paths puis en faisant `[...segments]` dans une fonction `generaterouterLink `et non `splitURL`

2023-01-10 14:51 UTC, esoubiran-aneo commented on apps/app/src/app/shared/util/services/favorites.service.ts
> +            url: root.children['primary'].segments.toString(),
On doit pouvoir faire plus simple en retournant un tableau qui contient tous les paths puis en faisant [...segments] dans une fonction `generaterouterLink `et non `splitURL` et ça permet de n'avoir à gérer qu'un unique cas dans la fonction.

2023-01-10 14:52 UTC, Faust1-2was-Aneo commented on apps/app/src/app/shared/util/services/favorites.service.ts
> +            url: root.children['primary'].segments.toString(),
Bien vu ! Je vais essayer ça

2023-01-11 10:09 UTC, esoubiran-aneo requested changes

2023-01-11 10:09 UTC, esoubiran-aneo commented on apps/app/src/app/shared/feature/the-favorites-navigation/the-favorites-navigation.component.ts
> +    return ['/', ...url];
le `...` d'une string, ça la décompose

2023-01-11 10:09 UTC, esoubiran-aneo commented on apps/app/src/app/shared/util/services/favorites.service.ts
> +  url: string | string[];
Juste `string[]` et ensuite, tu gères pour que s'il n'y a que 1 unique segment, ça aille dans un tableau

2023-01-11 16:21 UTC, esoubiran-aneo commented on apps/app/src/app/shared/util/services/favorites.service.ts
> +            url: root.children['primary'].segments.toString(),
Parfait !

2023-01-16 12:59 UTC, esoubiran-aneo approved these changes
Parfait ! Il doit falloir faire la même chose pour l'historique.

2023-01-16 13:15 UTC, merged