feat: use api package
aneoconsulting/ArmoniK.Admin.GUI pull request #464
Opened 2023-02-22 10:50 UTC by esoubiran-aneo

### 🔗 Linked issue

- [ ] Remove old code

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-02-22 13:40 UTC, Faust1-2was-Aneo requested changes

2023-02-22 13:40 UTC, Faust1-2was-Aneo commented on libs/shared/data-access/src/index.ts
> +export { ApplicationsClient } from '@aneoconsultingfr/armonik.api.angular';
Faire des imports de cette manière ne risque pas d'augmenter la taille du build ?

2023-02-22 13:40 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
>        - name: Build proto
You can also remove this part.

2023-02-22 13:42 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
>        - name: Build proto
```suggestion
```

2023-02-22 13:42 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
>          if: steps.proto-cache.outputs.cache-hit != 'true'
```suggestion
```

2023-02-22 13:42 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
>          run: yarn proto:generate
```suggestion
```

2023-02-22 13:43 UTC, Faust1-2was-Aneo requested changes

2023-02-22 13:43 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
>          run: yarn proto:generate
```suggestion
```

2023-02-23 13:40 UTC, esoubiran-aneo commented on libs/shared/data-access/src/index.ts
> +export { ApplicationsClient } from '@aneoconsultingfr/armonik.api.angular';
en soit, c'était pour tester au début que ça marchait bien mais je pense que je vais retirer tout ça.

2023-02-23 13:40 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
>          run: yarn proto:generate
Je ne suis pas sûr de comprendre ce qui change.

2023-02-23 13:41 UTC, Faust1-2was-Aneo commented on .github/workflows/cd-docker.yml
>          run: yarn proto:generate
On a plus besoin de build les protos maintenant. La ligne n'est plus utile.

2023-02-23 13:42 UTC, esoubiran-aneo commented
fix bug in UT libs/applications/data-access/src/lib/services/grpc-applications.service.spec.ts

2023-03-06 10:57 UTC, Faust1-2was-Aneo approved these changes

2023-03-06 10:58 UTC, merged