Add dockerfile for app and api
aneoconsulting/ArmoniK.Admin.GUI pull request #5
Opened 2022-04-25 10:00 UTC by esoubiran-aneo

- build(clarity): fix install size
- build(docker): create file for api
- build(docker): create file for app

2022-04-26 10:03 UTC, maurelleAneo commented on .github/workflows/docker-ci.yml
> +          username: dhaneo1
Ne doit pas être en secret aussi ?

2022-04-26 10:41 UTC, esoubiran-aneo commented on .github/workflows/docker-ci.yml
> +          username: dhaneo1
Je pense aussi mais comme [il est ici](https://github.com/aneoconsulting/ArmoniK.Core/blob/master/.github/workflows/build.yml#L216) en publique, je sais pas trop !

2022-04-28 07:22 UTC, esoubiran-aneo commented on .github/workflows/docker-ci.yml
> +          username: dhaneo1
@aneojgurhem c'est volontaire ? Parce que vous le faites aussi dans vos fichiers !

2022-04-28 08:13 UTC, aneojgurhem commented on .github/workflows/docker-ci.yml
> +          username: dhaneo1
Faudrait le mettre en secret. Pas encore eu le temps...

2022-04-28 08:15 UTC, aneojgurhem commented on .github/workflows/docker-ci.yml
> +          username: dhaneo1
DOCKER_HUB_USER, c'est fait pour vous

2022-04-28 08:27 UTC, maurelleAneo requested changes

2022-04-28 08:27 UTC, maurelleAneo commented on .github/workflows/cd-docker.yml
> +  push:
On envoie les images docker uniquement sur les PR de main et non sur les push non ?

2022-04-28 08:27 UTC, maurelleAneo commented on .github/workflows/ci-angular.yml
> +    branches-ignore:
pourquoi on ignore cette branche pour le ci d'angular ?

2022-04-28 08:48 UTC, esoubiran-aneo commented on .github/workflows/cd-docker.yml
> +  push:
Oui mais sur une pr, ça veut dire qu'on build l'image alors même que la pr n'est pas acceptée et on ne fera un push sur main que lors que une branch release est acceptée.

Donc en faisant cela, on build l'image uniquement lorsque la release est acceptée sur main

2022-04-28 08:49 UTC, esoubiran-aneo commented on .github/workflows/ci-angular.yml
> +    branches-ignore:
parce qu'on fait déjà les tests sur la pull request de release à main

2022-04-29 07:12 UTC, maurelleAneo requested changes

2022-04-29 07:12 UTC, maurelleAneo commented on .github/workflows/ci-angular.yml
> +    branches-ignore:
Ca va pour moi

2022-04-29 07:12 UTC, maurelleAneo commented on .github/workflows/ci-angular.yml
> +    branches:
Les branches listées ici sont les branches à partir desquelles les PR sont créées, donc dans notre fonctionnement en Gitflow on aura des feature/, release/ et hotfix/. On peut donc ignorer les branches main et develop

2022-04-29 07:44 UTC, merged