ci: add condition to run coverage on pr only
aneoconsulting/ArmoniK.Admin.GUI pull request #56
Opened 2022-06-03 14:53 UTC by esoubiran-aneo

2022-06-07 06:46 UTC, ngruelaneo commented
Pourquoi faire tourner le coverage uniquement sur les PRs? Perso je trouve aussi interessant de voir cela sur la branche main pour avoir une idée de l'évolution de couverture.

2022-06-07 06:47 UTC, ngruelaneo requested changes
Je ne trouve pas cela utile de limiter uniquement au PR. Il faut, au minimum, avoir le coverage du main.

2022-06-07 13:51 UTC, esoubiran-aneo commented
> Je ne trouve pas cela utile de limiter uniquement au PR. Il faut, au minimum, avoir le coverage du main.

C'est possible d'avoir une idée du workflow qu'il faudrait parce que je suis d'accord sur l'idée mais je ne sais pas comment cela doit se traduire !

2022-06-24 10:42 UTC, Barbapapazes commented
Ajouter la création d'artefacts et laisser le publish sur commit only

2022-06-28 13:20 UTC, esoubiran-aneo commented
> A mon avis tu peux faire tourner le coverage pour tous tes commits et garder ceux sur main plus longtemps

Ok beh je pense que c'est ce que je fais.

- Pour tous les commits, le coverage tourne
- Pour les pull request, un message est posté
- Pour les push sur main, un artéfact est créé

2022-06-28 13:22 UTC, aneojgurhem commented
Pour moi c'est bon, faut juste que tu résolves ton conflit

2022-06-29 14:37 UTC, ngruelaneo approved these changes

2022-06-29 14:37 UTC, merged