feat(cancel-session): cancel
aneoconsulting/ArmoniK.Admin.GUI pull request #58
Opened 2022-06-07 13:10 UTC by esoubiran-aneo

2022-06-07 16:55 UTC, aneojgurhem requested changes

2022-06-07 16:55 UTC, aneojgurhem commented on apps/api/src/app/core/proto/submitter_service.proto
> +message Empty {}
Pourquoi tu as une copie du proto (certes dégradée) qui se trouve dans ArmoniK.Api et non pas un submodule ou éventuellement, on peut regarder pour faire un packet propre à JS que tu pourrais inclure ? Je penche pour le submodule dans un premier temps et une fois qu'on sait faire le packet et le pousser comme il faut, on utilise la seconde approche. On le fait deja pour le C# donc ce n'est pas un soucis.

2022-06-07 16:55 UTC, aneojgurhem commented on apps/api/src/app/core/proto/submitter_service.ts
> +}
Ce fichier est clairement une traduction du fichier .proto au dessus. Est ce un fichier généré ? Si oui, il ne devrait pas être là. Si non, il devrait être possible de le générer d'une manière ou d'une autre en paramétrant ton projet.

2022-06-08 07:50 UTC, esoubiran-aneo commented on apps/api/src/app/core/proto/submitter_service.ts
> +}
pour un fichier généré, je dois le mettre où ?

2022-06-08 07:51 UTC, esoubiran-aneo commented on apps/api/src/app/core/proto/submitter_service.ts
> +}
et je dois le mettre dans le gitignore ou je peux l'envoyer sur github ?

2022-06-08 08:16 UTC, esoubiran-aneo commented on apps/api/src/app/core/proto/submitter_service.ts
> +}
et vrai, le générateur ne fonctionne pas et produit des types qui ne sont pas les bons donc ça sera des fichiers écrit à la main et je n'ajoute que ce qu'il faut dans le fichier proto pour ne pas en avoir trop et perdre le développeur avec trop de fonction

2022-06-08 08:19 UTC, esoubiran-aneo commented on apps/api/src/app/core/proto/submitter_service.proto
> +message Empty {}
parce que je n'ai pas besoin de tout ce qu'il y a dans les fichiers proto ! mais peut être faut-il faire un submodule effectivement ?

2022-06-08 13:00 UTC, esoubiran-aneo commented on apps/api/src/app/core/proto/submitter_service.proto
> +message Empty {}
mais carrément chaud pour qu'on en reparle @aneojgurhem

2022-06-09 15:41 UTC, aneojgurhem commented on apps/api/src/app/core/proto/submitter_service.ts
> +}
Pas de générateur à refaire !

2022-06-09 15:41 UTC, aneojgurhem commented on apps/api/src/app/core/proto/submitter_service.proto
> +message Empty {}
Tu peux utiliser `git submodule`

2022-06-10 08:10 UTC, esoubiran-aneo commented on apps/api/src/app/core/proto/submitter_service.proto
> +message Empty {}
done

2022-06-10 08:12 UTC, aneojgurhem approved these changes

2022-06-10 08:14 UTC, merged