chore: refresh service tests
aneoconsulting/ArmoniK.Admin.GUI pull request #588
Opened 2023-09-13 09:46 UTC by Faust1-2was-Aneo

2023-10-02 08:11 UTC, yannick-aneo requested changes

2023-10-02 08:11 UTC, yannick-aneo commented on src/app/services/auto-refresh.service.ts
> +   * @param stopIntervalSubject The interval can be stoped if with this subjet.
```suggestion
   * @param intervalSubject The observable is depending on this subject, so if the the subject has a new value, the observable will be updated.
   * @param stopIntervalSubject The interval can be stopped if with this subject.
```

2023-10-02 08:11 UTC, yannick-aneo commented on src/app/services/auto-refresh.service.spec.ts
> +    it('Should not indicates the interval when it is set below 0', () => {
```suggestion
    it('Should not show the interval when it is set to 0', () => {
      expect(service.autoRefreshTooltip(0)).toBe('Auto-refresh is disabled');
    });
    it('Should not show the interval when it is set below 0', () => {
```

2023-10-02 12:54 UTC, Faust1-2was-Aneo commented on src/app/services/auto-refresh.service.spec.ts
>        const intervalSubjet: BehaviorSubject<number> = new BehaviorSubject(1);
good point, i'll correct it

2023-10-03 07:35 UTC, yannick-aneo approved these changes

2023-10-03 07:35 UTC, merged