Create UI for tasks in dashboard
aneoconsulting/ArmoniK.Admin.GUI pull request #6
Opened 2022-04-28 09:28 UTC by esoubiran-aneo

2022-04-29 07:43 UTC, maurelleAneo requested changes

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/cards.module.ts
> +export class CardsModule {}
Renommer ce module : TasksModue car il va gérer toute la partie relative aux entités tâches

Il faut également que ce module soit à part entière et donc ne fasse pas partie du module Dashboard

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/dashboard.component.html
> +<app-pages-dashboard-cards></app-pages-dashboard-cards>
A supprimer

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/dashboard.module.ts
> +  imports: [CommonModule, CardsModule],
A supprimer

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +    DashboardModule,
Tu n'as pas besoin d'importer le module dashboard ici

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/cards.component.ts
> +  selector: 'app-pages-dashboard-cards',
Pense à changer le sélecteur suite à la modification de ton module

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/card/card.module.ts
> +export class CardModule {}
Supprimer ce module car cette partie ne sera qu'un composant utilisé dans le module Tasks. 
Tu retrouvera ton composant dans un dossier components du module Tasks, et ce fichier devra être remplacé par un fichier index.ts à la racine du dossier components pour pouvoir exporter ton composant Task

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/card/card.component.ts
> +export class CardComponent {
Renommer ce composant en TaskComponent

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/card/card.component.ts
> +  selector: 'app-pages-dashboard-cards-card',
pense à renommer ton sélecteur suite à la migration de ton module Tasks hors de Dashboard

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/card/card.component.scss
> +.flex {
Pour la partie flex, tu peux isntaller le package flex-layout d'angular qui te permettra de réaliser tout ce style directement depuis le html

2022-04-29 07:43 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.module.ts
>      RouterModule.forRoot([
Tu pourra ajouter une redirection vers la page des Tasks avec un bouton depuis le dashboard par exemple

2022-05-02 07:12 UTC, maurelleAneo requested changes

2022-05-02 07:12 UTC, maurelleAneo commented on libs/ui/src/lib/card/card.component.scss
> +  background-color: hsl(93, 67%, 38%);
On utilisera ici soit : 
- Les couleurs de clarity (si possible de les intégrer)
- Les couleurs de clarity en créant un fichier spécifique

2022-05-02 07:12 UTC, maurelleAneo commented on libs/ui/src/lib/card/index.ts
> +export * from './card.component';
Il faut aussi exporter le card.module

2022-05-02 07:12 UTC, maurelleAneo commented on libs/ui/src/lib/card/card.module.ts
> +export class CardModule {}
Il faut également penser à exporter le dossier lib/card dans le fichier index.ts à la racine de lib

2022-05-02 07:12 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +            loadChildren: () =>
Tu peux supprimer l'import de DashboardComponent

2022-05-02 07:12 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX tâches complétées </span>
Pense à faire les traductions nécessaires (même si ce sont des données en dur pour le moment)

2022-05-02 09:43 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX tâches complétées </span>
Oui, dès que j'ai la traduction à ma disposition sur dévelop

2022-05-02 11:58 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/dashboard/cards/card/card.component.ts
> +  selector: 'app-pages-dashboard-cards-card',
C'est fait depuis que la card est passé dans la lib ui

2022-05-02 11:58 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/pages.module.ts
>      RouterModule.forRoot([
done

2022-05-02 11:58 UTC, esoubiran-aneo commented on libs/ui/src/lib/card/card.component.scss
> +  background-color: hsl(93, 67%, 38%);
les couleurs sont mises en variable dans le style global comme on a vu qu'on ne pouvait pas les intégrer directement depuis clarity

2022-05-02 11:58 UTC, esoubiran-aneo commented on libs/ui/src/lib/card/index.ts
> +export * from './card.component';
done

2022-05-02 12:00 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +            loadChildren: () =>
done

2022-05-02 12:00 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +    DashboardModule,
supprimé

2022-05-02 13:45 UTC, maurelleAneo requested changes

2022-05-02 13:45 UTC, maurelleAneo commented on libs/ui/src/lib/card/card.component.scss
> +  $types: ('success', 'warn', 'danger');
Tu peux mieux nommer cette variable : utilises par exemple dotTypes ou dotClasses pour que l'on comprenne d'un coup d'oeil de quoi tu parles sans avoir à aller chercher dans le composant à quoi cela correspond (oui je chipote :) )

2022-05-02 13:45 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +    <ui-card [dot]="'success'">
je crois qu'ici au lieu de mettre [dot]="'success'" avec des double quotes additionnées de simples quotes tu peux faire : dot="success" directement

2022-05-02 14:12 UTC, esoubiran-aneo commented on libs/ui/src/lib/card/card.component.scss
> +  $types: ('success', 'warn', 'danger');
done

2022-05-02 14:13 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +    <ui-card [dot]="'success'">
done

2022-05-04 08:50 UTC, maurelleAneo requested changes

2022-05-04 08:50 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX tâches complétées </span>
Pense à pull develop pour pouvoir faire les changements nécessaires ici

2022-05-04 09:54 UTC, esoubiran-aneo commented
done

2022-05-04 14:28 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX tâches complétées </span>
done

2022-05-04 14:28 UTC, esoubiran-aneo commented on libs/ui/src/lib/card/card.module.ts
> +export class CardModule {}
done

2022-05-04 14:34 UTC, maurelleAneo requested changes

2022-05-04 14:34 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX {{ 'dashboard.tasks.in-progress' | translate }} </span>
pareil pour le XX

2022-05-04 14:34 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX {{ 'dashboard.tasks.error' | translate }} </span>
pareil pour le XX

2022-05-04 15:06 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/dashboard/components/tasks-sum-up/tasks-sum-up.component.html
> +      <span title> XX {{ 'dashboard.tasks.completed' | translate }} </span>
done

2022-05-04 15:10 UTC, maurelleAneo submitted a review, later dismissed

2022-05-04 15:11 UTC, maurelleAneo commented
Apparemment certains tests ne passent pas encore !

2022-05-05 12:01 UTC, esoubiran-aneo commented
#18 permet de résoudre le problème

2022-05-09 06:55 UTC, maurelleAneo approved these changes

2022-05-09 06:55 UTC, merged