chore: tests for utils service
aneoconsulting/ArmoniK.Admin.GUI pull request #636
Opened 2023-09-27 09:42 UTC by Faust1-2was-Aneo

2023-10-06 09:22 UTC, Faust1-2was-Aneo commented
In draft until #689 is merged and tested here

2023-10-09 08:23 UTC, yannick-aneo requested changes

2023-10-09 08:23 UTC, yannick-aneo commented on src/app/services/utils.service.spec.ts
> +    it('Should throw an error if its definition is not in the filtersDefinition', () => {
```suggestion
    it('Should throw an error if its definitions are not in the filtersDefinition', () => {
```

2023-10-10 07:40 UTC, yannick-aneo approved these changes

2023-10-10 07:43 UTC, merged