Fetch tasks using gRPC
aneoconsulting/ArmoniK.Admin.GUI pull request #7
Opened 2022-04-28 10:36 UTC by esoubiran-aneo

2022-04-29 10:22 UTC, maurelleAneo requested changes

2022-04-29 10:22 UTC, maurelleAneo commented on apps/api/src/app/app.controller.ts
>  export class AppController {
L'idée ici est de supprimer de controller d'App mais d'avoir un module par entité donc un module spécifique pour les tasks. Dans chaque module il faudrait y a voir à minima un controller spécifique. Dans l'idéal, il faudrait aussi y avoir le service interface utilisé par le controller utilisé par gRPC (à voir du coup pour un nouveau découpage des services avec ArmoniK)

2022-05-02 07:33 UTC, lemaitre-aneo commented on .env.example
> +GRPC_URL=<the_grpc_url>
à voir ensemble plus tard, mais cette variable pourra être définie directement par kubernetes avec la bonne valeur

2022-05-02 07:35 UTC, lemaitre-aneo commented on apps/api/src/app/app.controller.ts
> +        Statuses: ['TASK_STATUS_FAILED', 'TASK_STATUS_COMPLETED', 6, 0, 9],
Il faudra penser à récupérer la liste des status depuis les Proto

2022-05-02 07:37 UTC, lemaitre-aneo reviewed
à part 2-3 remarques à garder en tête pour le future, je ne vois pas de problème.

2022-05-02 12:02 UTC, esoubiran-aneo commented on libs/interfaces/src/lib/TasksStatus.ts
> +export enum TaskStatus {
effectivement, c'est plus explicite !

2022-05-02 12:06 UTC, esoubiran-aneo commented on libs/interfaces/src/lib/TasksStatus.ts
> +export enum TaskStatus {
done

2022-05-02 12:11 UTC, esoubiran-aneo commented on libs/interfaces/src/lib/TasksStatus.ts
> +export enum TaskStatus {
done

2022-05-02 12:11 UTC, esoubiran-aneo commented on libs/interfaces/src/index.ts
> +export * from './lib/TasksStatus';
done

2022-05-02 12:12 UTC, esoubiran-aneo commented on apps/api/src/proto/Submitter.proto
> +syntax = "proto3";
ne fonctionne pas

2022-05-02 12:16 UTC, esoubiran-aneo commented on apps/app/src/app/app.component.ts
> +import { Message } from '@armonik.admin.gui/interfaces';
done

2022-05-02 12:17 UTC, esoubiran-aneo commented on .env.example
> +GRPC_URL=<the_grpc_url>
Effectivement lors du déploiement ! Mais en dev, on en a besoin !

2022-05-02 14:53 UTC, esoubiran-aneo commented
Je modifierai en fonction de ce qu'on fera avec l'équipe Armonik, donc ça reste en attente

2022-05-04 08:56 UTC, maurelleAneo reviewed
Il faudra continuer cette PR une fois celle des proto terminée

2022-05-23 15:33 UTC, closed without merging