Create UI for sessions
aneoconsulting/ArmoniK.Admin.GUI pull request #8
Opened 2022-04-28 14:11 UTC by esoubiran-aneo

2022-04-29 12:56 UTC, maurelleAneo requested changes

2022-04-29 12:56 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.html
> +    <clr-dg-row *ngFor="let session of sessions">
La bonne pratique sur les boucles *ngFor c'est de rajouter un attribut trackBy (tu peux regarder dans la doc), qui fonctionne un peu comme un index primaire de bdd. Cela permet à la vue de recharger plus efficacement les données de la liste par comparaison entre la valeur indiquée en index et les valeurs provenant de la nouvelle liste à charger

2022-05-02 14:16 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/pages.module.ts
>            { path: 'dashboard', component: DashboardComponent },
Oui, c'est fait mais sur la branche de travail de dashboard !

2022-05-02 14:24 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.html
> +    <clr-dg-row *ngFor="let session of sessions">
done

2022-05-04 08:58 UTC, maurelleAneo requested changes

2022-05-04 08:58 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.ts
> +  identifySession(_: number, session: Session) {
retour de fonction manquant
Et mieux vaut renommer ta fonction trackBySession pour que l'on sache à quoi cela sert exactement

2022-05-04 08:58 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.html
> +  <h1>Toutes les sessions</h1>
Tu pourra pull la develop pour appliquer les traductions nécessaires dans ce fichier

2022-05-04 10:05 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.html
> +  <h1>Toutes les sessions</h1>
done

2022-05-04 10:06 UTC, esoubiran-aneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.ts
> +  identifySession(_: number, session: Session) {
done

2022-05-05 13:07 UTC, esoubiran-aneo commented
Le test PR (ci apps app / run (test app) échoue mais c'est normal, il utilise les fichiers du premier commit (étrange) (#18 permet de résoudre le souci)

2022-05-09 07:02 UTC, maurelleAneo requested changes

2022-05-09 07:02 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/modules/sessions/sessions.component.ts
> +type Session = {
Pour ça on va plutôt faire un dossier /entities dans /core pour placer les différents fichiers de typage des entités

2022-05-10 09:02 UTC, maurelleAneo requested changes

2022-05-10 09:02 UTC, maurelleAneo commented on apps/app/src/app/modules/core/entities/Session.entity.ts
> +export type Session = {
Le nom du fichier doit être écrit en minuscule :)

2022-05-10 09:21 UTC, esoubiran-aneo commented on apps/app/src/app/modules/core/entities/Session.entity.ts
> +export type Session = {
coup dur pour moi mdrrr, on va y arriver !

2022-05-10 09:36 UTC, maurelleAneo approved these changes

2022-05-10 09:36 UTC, merged