Add translation service
aneoconsulting/ArmoniK.Admin.GUI pull request #9
Opened 2022-04-28 15:05 UTC by esoubiran-aneo

Not ready to merge

2022-04-29 14:05 UTC, maurelleAneo requested changes

2022-04-29 14:05 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.component.html
> +          {{ language.name | uppercase }}
Du coup ici rajouter une traduction des noms des langues en utilisant leur code comme clef dans le fichier de traduction

2022-05-02 14:26 UTC, esoubiran-aneo commented on apps/app/src/app/app.module.ts
>        { path: '*', children: [{ path: '*', component: PagesComponent }] },
Oui, mais ce n'est pas le sujet de cette PR !

2022-05-02 14:31 UTC, esoubiran-aneo commented on apps/app/src/app/app.module.ts
>        { path: '*', children: [{ path: '*', component: PagesComponent }] },
fix in #13

2022-05-02 14:32 UTC, esoubiran-aneo commented on apps/app/src/app/app.module.ts
>  import { PagesComponent } from './modules/pages/pages.component';
done

2022-05-02 14:32 UTC, esoubiran-aneo commented on apps/app/src/app/app.module.ts
>  import { PagesModule } from './modules/pages/pages.module';
done

2022-05-03 13:08 UTC, maurelleAneo commented on apps/app/src/app/app.component.ts
> +    this.translationService.initLocale(LanguageCode.EN);
faire ça dans le constructeur de AppModule

2022-05-03 13:15 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +    TranslateModule.forChild(),
pas besoin normalement puisqu'il est déclaré dans App Module

2022-05-03 13:18 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.component.html
> +      <li *ngFor="let language of languages">
pour chaque ngFor que tu créés la bonne pratique est d'ajouter un trackBy pour optimiser les perfs

2022-05-03 13:18 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.component.html
>          *ngFor="let link of links"
pareil ajouter un trackBy

2022-05-03 13:20 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.component.ts
> +      label: this.translateService.get('sidenav.dashboard'),
tu peux utiliser get ici mais l'inconvénient est qu'il te renvoie un observable. Pour plus de praticité dans l'avenir on peut utiliser la méthode .instant qui te renvoi juste un string et qui permet de traduire à l'instant donné ta clef.
Comme tes fichier de langues ont été générés au début de l'app, logiquement il n'y a pas de délai de traduction donc instant peut être utilisé -> à tester

2022-05-04 08:14 UTC, maurelleAneo requested changes

2022-05-04 08:14 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.component.ts
>  export class PagesComponent {
De manière générale, n'oublies pas d'ajouter les retours de chacune de tes fonctions, exemple :
`public trackByLabel(_: number, item: Link): string {
    return item.label;
  }`

2022-05-04 08:14 UTC, maurelleAneo commented on apps/app/src/app/modules/core/services/translation.service.ts
> +export class TranslationService {
De manière générale n'oublie pas d'ajouter les retours de chacune des tes fonctions

2022-05-04 08:14 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +  providers: [TranslationService, LocaleProvider],
Si ton service TranslationService est en providedIn: 'root' logiquement tu n'as pas à le placer dans le provider le pages car il est directement injectable via le constructeur

2022-05-04 08:14 UTC, maurelleAneo commented on apps/app/src/app/modules/pages/pages.module.ts
> +  providers: [TranslationService, LocaleProvider],
De même si tu provides LocaleProvider dans AppModule, il devrait logiquement être également disponible dans ses enfants (à vérifier)

2022-05-04 08:47 UTC, maurelleAneo approved these changes

2022-05-04 08:48 UTC, merged